"""rom - add multi

Revision ID: 1.6.3
Revises: 1.6.2
Create Date: 2023-04-10 16:21:34.680282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1.6.3'
down_revision = '1.6.2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roms', sa.Column('multi', sa.Boolean(), nullable=True))
    op.add_column('roms', sa.Column('files', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roms', 'files')
    op.drop_column('roms', 'multi')
    # ### end Alembic commands ###
