"""add platform name to rom

Revision ID: 1.7.2
Revises: 1.7.1
Create Date: 2023-04-17 12:03:19.163501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1.7.2'
down_revision = '1.7.1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roms") as batch_op:
        batch_op.add_column(sa.Column('p_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('url_cover', sa.Text(), nullable=True))
        batch_op.alter_column('name', new_column_name='r_name', type_=sa.String(length=150), existing_type=sa.String(length=150))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roms") as batch_op:
        batch_op.drop_column('url_cover')
        batch_op.drop_column('p_name')
        batch_op.alter_column('r_name', new_column_name='name', type_=sa.String(length=150), existing_type=sa.String(length=150))
    # ### end Alembic commands ###
