<script setup lang="ts">
// CollectionTile — collection card (Home row + /collections grid). Feature
// composite that wraps CollectionMosaic + name + count. `kind` overlays
// "Smart" or "Virtual" badge. `variant` controls sizing ("row" = 150px
// fixed, "grid" = fills cell).
import { RIcon, RTooltip } from "@v2/lib";
import { computed, ref } from "vue";
import { useI18n } from "vue-i18n";
import { useRouter } from "vue-router";
import CollectionMosaic from "@/v2/components/Collections/CollectionMosaic.vue";
import {
  pendingMorphName,
  useViewTransition,
} from "@/v2/composables/useViewTransition";

defineOptions({ inheritAttrs: false });

type Variant = "row" | "grid";
type Kind = "regular" | "virtual" | "smart";

interface Props {
  name: string;
  romCount?: number;
  covers?: (string | null | undefined)[];
  to: string | object;
  variant?: Variant;
  kind?: Kind;
  /** Owner-set visibility. Drives the private-lock badge. Only meaningful
   *  for regular/smart collections — virtual collections are
   *  autogenerated and never carry a public/private state. */
  isPublic?: boolean;
  /** Stable id used to derive the shared-element morph tag. Optional —
   *  if absent the tile still navigates but won't participate in the
   *  morph (some callers pass a virtual/smart wrapper object). */
  id?: number | string;
}

const props = withDefaults(defineProps<Props>(), {
  romCount: 0,
  covers: () => [],
  variant: "row",
  kind: "regular",
  isPublic: undefined,
  id: undefined,
});

const { t } = useI18n();

// Kind badge — smart/virtual collapse to an icon chip; the tooltip
// carries the word. Regular collections show no kind badge.
const kindBadge = computed<{ icon: string; label: string } | null>(() => {
  if (props.kind === "smart") {
    return { icon: "mdi-flash", label: t("collection.kind-smart") };
  }
  if (props.kind === "virtual") {
    return { icon: "mdi-bookmark-box", label: t("collection.kind-virtual") };
  }
  return null;
});

// Private-lock badge — only for owner-managed kinds (regular/smart).
// Virtual collections are autogenerated and have no visibility state.
const isPrivate = computed(
  () => props.kind !== "virtual" && props.isPublic === false,
);

// Shared-element morph between the tile's CollectionMosaic and the
// CollectionMosaic shown in the Collection view's InfoPanel cover slot.
// The tag includes the kind so regular/virtual/smart with overlapping
// numeric ids can never collide.
const router = useRouter();
const coverEl = ref<HTMLElement | null>(null);
const { morphTransition } = useViewTransition();

const morphName = computed(() =>
  props.id != null ? `coll-cover-${props.kind}-${props.id}` : null,
);

function onTileClick(e: MouseEvent) {
  if (e.metaKey || e.ctrlKey || e.shiftKey || e.altKey || e.button !== 0) {
    return;
  }
  if (!coverEl.value || !morphName.value) return;
  if (typeof props.to !== "string") return;
  e.preventDefault();
  const target = props.to;
  morphTransition({ el: coverEl.value, name: morphName.value }, async () => {
    await router.push(target);
  });
}

const morphStyle = computed(() =>
  morphName.value && pendingMorphName.value === morphName.value
    ? { viewTransitionName: morphName.value }
    : undefined,
);
</script>

<template>
  <router-link
    :to="to"
    v-bind="$attrs"
    class="coll-tile"
    :class="[`coll-tile--${variant}`]"
    :data-focus-key="id != null ? `collection-${kind}-${id}` : undefined"
    @click="onTileClick"
  >
    <div ref="coverEl" class="coll-tile__cover" :style="morphStyle">
      <CollectionMosaic :covers="covers" />
      <RTooltip v-if="kindBadge" :text="kindBadge.label" location="top">
        <template #activator="{ props: tip }">
          <span
            v-bind="tip"
            class="coll-tile__kind"
            :class="[`coll-tile__kind--${kind}`]"
            :aria-label="kindBadge.label"
          >
            <RIcon :icon="kindBadge.icon" size="18" />
          </span>
        </template>
      </RTooltip>
      <RTooltip v-if="isPrivate" :text="t('collection.private')" location="top">
        <template #activator="{ props: tip }">
          <span
            v-bind="tip"
            class="coll-tile__lock"
            :aria-label="t('collection.private')"
          >
            <RIcon icon="mdi-lock" size="18" />
          </span>
        </template>
      </RTooltip>
    </div>
    <div class="coll-tile__name">
      {{ name }}
    </div>
    <div class="coll-tile__count">
      {{ t("collection.games-count", romCount, { named: { n: romCount } }) }}
    </div>
  </router-link>
</template>

<style scoped>
.coll-tile {
  display: flex;
  flex-direction: column;
  gap: 10px;
  color: var(--r-color-fg);
  text-decoration: none;
  cursor: pointer;
}

.coll-tile--row {
  width: 150px;
  flex-shrink: 0;
}

.coll-tile__cover {
  position: relative;
  box-shadow: var(--r-elev-1);
  border-radius: var(--r-radius-lg);
  overflow: hidden;
  transition:
    transform var(--r-motion-fast),
    box-shadow var(--r-motion-fast);
}

/* Hover gated to mouse/touch — keeps a parked cursor from competing
   with the focused tile when driving with a gamepad. */
html[data-input="mouse"] .coll-tile:hover .coll-tile__cover,
html[data-input="touch"] .coll-tile:hover .coll-tile__cover,
.coll-tile:focus-visible .coll-tile__cover {
  transform: translateY(-2px);
  box-shadow: var(--r-elev-2);
}

/* Keyboard / gamepad focus — ring + brand glow on the cover, brighten
   the name. Matches the v1 console card visual language. */
.coll-tile:focus-visible {
  outline: none;
}
.coll-tile:focus-visible .coll-tile__cover {
  box-shadow:
    0 8px 28px color-mix(in srgb, black 40%, transparent),
    0 0 0 2px var(--r-color-brand-primary),
    0 0 18px color-mix(in srgb, var(--r-color-brand-primary) 55%, transparent);
}
.coll-tile:focus-visible .coll-tile__name {
  color: var(--r-color-fg);
}

.coll-tile__kind,
.coll-tile__lock {
  position: absolute;
  top: 8px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  /* Match the GameCard corner-badge footprint (icon + padding +
     hairline border, circular) so collection cards read as the same
     family. */
  padding: 4px;
  border-radius: 50%;
  border: 1px solid var(--r-color-overlay-border);
  color: var(--r-color-overlay-fg);
}

/* Kind chip, top-left. Virtual = brand (cool); smart = accent (warm) so
   the two computed kinds read apart at a glance. */
.coll-tile__kind {
  left: 8px;
  background: color-mix(
    in srgb,
    var(--r-color-brand-primary-hover) 85%,
    transparent
  );
}

.coll-tile__kind--smart {
  background: color-mix(in srgb, var(--r-color-brand-accent) 85%, transparent);
}

/* Private — neutral dark-glass chip, top-right, so it reads as a
   status marker distinct from the brand-tinted kind chip. */
.coll-tile__lock {
  right: 8px;
  background: var(--r-color-overlay-scrim-strong);
}

.coll-tile__name {
  font-size: 12.5px;
  font-weight: var(--r-font-weight-semibold);
  color: var(--r-color-fg-secondary);
  padding: 0 2px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.coll-tile__count {
  font-size: 11px;
  color: var(--r-color-fg-muted);
  padding: 0 2px;
}

html[data-bp~="xs"] .coll-tile--row {
  width: 120px;
}
</style>
