#!/command/with-contenv bash

set -o errexit
set -o nounset
set -o pipefail
shopt -s inherit_errexit

ROMM_LOG_TAG="rq-scheduler"
# shellcheck source=SCRIPTDIR/../../scripts/lib.sh
source /etc/s6-overlay/scripts/lib.sh

record_process_group

if [[ ${ENABLE_SCHEDULED_RESCAN:-false} != "true" &&
	${ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB:-false} != "true" &&
	${ENABLE_SCHEDULED_UPDATE_LAUNCHBOX_METADATA:-false} != "true" &&
	${ENABLE_SCHEDULED_CLEANUP_ORPHANED_RESOURCES:-false} != "true" ]]; then
	debug_log "No scheduled tasks are enabled, not starting the RQ scheduler"
	disable_service
fi

info_log "Starting RQ scheduler"

export RQ_REDIS_HOST="${REDIS_HOST:-127.0.0.1}"
export RQ_REDIS_PORT="${REDIS_PORT:-6379}"
export RQ_REDIS_USERNAME="${REDIS_USERNAME:-""}"
export RQ_REDIS_PASSWORD="${REDIS_PASSWORD:-""}"
export RQ_REDIS_DB="${REDIS_DB:-0}"
export RQ_REDIS_SSL="${REDIS_SSL:-0}"

exec rqscheduler --path /backend
