name: Trunk Check setup
description: Set up dependencies for Trunk Check

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v5.0.0
      with:
        node-version: 18

    - name: Install dependencies
      shell: bash
      run: npm install
      working-directory: frontend
