"""empty message

Revision ID: 0015_mobygames_data
Revises: 0014_asset_files
Create Date: 2024-02-13 17:57:25.936825

"""

import sqlalchemy as sa
from alembic import op
from utils.database import CustomJSON

# revision identifiers, used by Alembic.
revision = "0015_mobygames_data"
down_revision = "0014_asset_files"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("platforms", schema=None) as batch_op:
        batch_op.add_column(sa.Column("moby_id", sa.Integer(), nullable=True))

    with op.batch_alter_table("roms", schema=None) as batch_op:
        batch_op.add_column(sa.Column("moby_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("moby_metadata", CustomJSON(), nullable=True))

    with op.batch_alter_table("roms", schema=None) as batch_op:
        batch_op.execute("update roms set moby_metadata = JSON_OBJECT()")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roms", schema=None) as batch_op:
        batch_op.drop_column("moby_metadata")
        batch_op.drop_column("moby_id")

    with op.batch_alter_table("platforms", schema=None) as batch_op:
        batch_op.drop_column("moby_id")

    # ### end Alembic commands ###
