"""empty message

Revision ID: 0017_firmware
Revises: 0016_user_last_login_active
Create Date: 2024-04-10 13:50:39.208700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0017_firmware'
down_revision = '0016_user_last_login_active'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmwares',
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_name', sa.String(length=450), nullable=False),
    sa.Column('file_name_no_tags', sa.String(length=450), nullable=False),
    sa.Column('file_name_no_ext', sa.String(length=450), nullable=False),
    sa.Column('file_extension', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firmwares')
    # ### end Alembic commands ###
