"""empty message

Revision ID: 0019_resources_refactor
Revises: 0018_firmware
Create Date: 2024-05-05 11:20:54.243980

"""

import os
from urllib.parse import quote

import sqlalchemy as sa
from alembic import op
from config import RESOURCES_BASE_PATH

# revision identifiers, used by Alembic.
revision = "0019_resources_refactor"
down_revision = "0018_firmware"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Get the database connection
    connection = op.get_bind()

    # Fetch all entries from the roms table
    platforms = connection.execute(sa.text("select id, slug from platforms"))
    platforms_row = platforms.fetchall()
    roms = connection.execute(
        sa.text(
            "SELECT id, name, platform_id, path_cover_s, path_cover_l, path_screenshots FROM roms"
        )
    )
    roms_row = roms.fetchall()

    for rom in roms_row:
        platform_slug = ""
        for platform in platforms_row:
            if platform.id == rom.platform_id:
                platform_slug = platform.slug
        old_folder_name = f"{RESOURCES_BASE_PATH}/{platform_slug}/{rom.name}"
        new_folder_name = f"{RESOURCES_BASE_PATH}/{platform_slug}/{rom.id}"
        print(f"MIGRATION: old folder: {old_folder_name}")
        print(f"MIGRATION: new folder: {new_folder_name}")
        if os.path.exists(old_folder_name):
            os.rename(old_folder_name, new_folder_name)
        else:
            print(f"MIGRATION - ERROR: Folder '{old_folder_name}' does not exist.")

        import re

        quoted_rom_name = re.escape(quote(rom.name))
        print(quoted_rom_name)
        updated_path_cover_s = re.sub(quoted_rom_name, str(rom.id), rom.path_cover_s)
        connection.execute(
            sa.text(
                f"UPDATE roms SET path_cover_s = '{updated_path_cover_s}' WHERE id = {rom.id}"
            )
        )
        updated_path_cover_l = re.sub(quoted_rom_name, str(rom.id), rom.path_cover_l)
        connection.execute(
            sa.text(
                f"UPDATE roms SET path_cover_l = '{updated_path_cover_l}' WHERE id = {rom.id}"
            )
        )
        updated_path_screenshots = re.sub(
            quoted_rom_name, str(rom.id), rom.path_screenshots
        )
        connection.execute(
            sa.text(
                f"UPDATE roms SET path_screenshots = '{updated_path_screenshots}' WHERE id = {rom.id}"
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
