"""empty message

Revision ID: 0019_add_games_extra_metadata
Revises: 0018_increase_file_extension
Create Date: 2024-02-01 17:53:53.562928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0019_add_games_extra_metadata'
down_revision = '0018_increase_file_extension'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_rating', sa.String(length=350), nullable=True))
        batch_op.add_column(sa.Column('genres', sa.JSON(), nullable=True))
        batch_op.alter_column('file_extension',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        
    with op.batch_alter_table('roms', schema=None) as batch_op:
        # Set default values for JSON columns
        batch_op.execute("UPDATE roms SET genres = '[]'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roms', schema=None) as batch_op:
        batch_op.alter_column('file_extension',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('genres')
        batch_op.drop_column('total_rating')

    # ### end Alembic commands ###
