"""empty message

Revision ID: 0020_update_at_added
Revises: 0019_resources_refactor
Create Date: 2024-06-27 11:33:06.962897

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0020_update_at_added"
down_revision = "0019_resources_refactor"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("firmware", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("platforms", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("rom_notes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.drop_column("last_edited_at")

    with op.batch_alter_table("roms", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("roms", schema=None) as batch_op:
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("rom_notes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "last_edited_at",
                mysql.DATETIME(),
                server_default=sa.text("current_timestamp()"),
                nullable=False,
            )
        )
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("platforms", schema=None) as batch_op:
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("firmware", schema=None) as batch_op:
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###
