"""empty message

Revision ID: 0021_user_rom_props
Revises: 0020_created_and_updated
Create Date: 2024-06-29 00:11:51.800988

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0021_user_rom_props"
down_revision = "0020_created_and_updated"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # TODO: adjust to rename instead of drop + create
    op.create_table(
        "user_rom_props",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("note_raw_markdown", sa.Text(), nullable=False),
        sa.Column("note_is_public", sa.Boolean(), nullable=True),
        sa.Column("rom_is_main_sibling", sa.Boolean(), nullable=True),
        sa.Column("rom_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["rom_id"], ["roms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rom_id", "user_id", name="unique_rom_user_props"),
    )
    with op.batch_alter_table("rom_notes", schema=None) as batch_op:
        batch_op.drop_index("unique_rom_user_note")

    op.drop_table("rom_notes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rom_notes",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("raw_markdown", mysql.TEXT(), nullable=False),
        sa.Column(
            "is_public",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "rom_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("current_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(),
            server_default=sa.text("current_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rom_id"], ["roms.id"], name="rom_notes_ibfk_1", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="rom_notes_ibfk_2", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        mariadb_collate="utf8mb4_general_ci",
        mariadb_default_charset="utf8mb4",
        mariadb_engine="InnoDB",
    )
    with op.batch_alter_table("rom_notes", schema=None) as batch_op:
        batch_op.create_index(
            "unique_rom_user_note", ["rom_id", "user_id"], unique=True
        )

    op.drop_table("user_rom_props")
    # ### end Alembic commands ###
