"""empty message

Revision ID: 0021_fav_sibling
Revises: 0020_created_and_updated
Create Date: 2024-06-27 18:04:55.707623

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0021_fav_sibling"
down_revision = "0020_created_and_updated"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roms", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "fav_sibling", sa.Boolean(), nullable=True, server_default=sa.false()
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roms", schema=None) as batch_op:
        batch_op.drop_column("fav_sibling")

    # ### end Alembic commands ###
