"""empty message

Revision ID: 0036_screenscraper_platforms_id
Revises: 0035_screenscraper
Create Date: 2025-01-02 18:58:55.557123

"""

import sqlalchemy as sa
from alembic import op

from handler.metadata.ss_handler import SCREENSAVER_PLATFORM_LIST

# revision identifiers, used by Alembic.
revision = "0036_screenscraper_platforms_id"
down_revision = "0035_screenscraper"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    for slug, ss_platform in SCREENSAVER_PLATFORM_LIST.items():
        connection.execute(
            sa.text("UPDATE platforms SET ss_id = :ss_id WHERE slug = :slug"),
            {"ss_id": ss_platform["id"], "slug": slug.value},
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
