"""add_oidc_sub_to_users

Revision ID: 0055_add_oidc_sub_to_users
Revises: 0054_add_platform_metadata_slugs
Create Date: 2025-01-07 11:16:53.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0055_add_oidc_sub_to_users"
down_revision = "0054_add_platform_metadata_slugs"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("oidc_sub", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_users_oidc_sub"), "users", ["oidc_sub"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_oidc_sub"), table_name="users")
    op.drop_column("users", "oidc_sub")
    # ### end Alembic commands ###
