"""Materialize virtual collection membership into an indexed table

``virtual_collections`` was a view that unnested five JSON arrays per rom on
every read, so both the collection list and opening a single collection scanned
the whole library (~40s on 90k roms, regardless of how few roms the collection
held: the name is computed inside the view, so nothing can be narrowed down
early).

Membership now lives in a real table, ``virtual_collection_roms``, holding one
narrow row per (rom, type, name). It is filled from the ``generated_*`` columns
added in 0098 and kept in sync by triggers on ``roms`` (no application hook, no
background job), with rom deletions handled by the foreign key's cascade. The
view is redefined as an aggregate over that table, so a single collection is an
indexed lookup and the list never touches raw provider metadata again.

Notes:
- The backfill pays the old derive-once cost a single time, during this
  migration, instead of on every request.
- Covers are denormalized onto the membership rows, so the list does not join
  back to the (large) roms table; the handler caps how many it reads per
  collection.
- The description now reads "Autogenerated <name> collection" on PostgreSQL
  too; it previously interpolated the type there and the name on MariaDB.
- Names are truncated to the column width instead of relying on the JSON_TABLE
  column type, which would abort the rom write under strict mode.

Revision ID: 0101_virtual_collection_roms
Revises: 0100_roms_facets_table
Create Date: 2026-07-22 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op  # type: ignore[attr-defined]
from sqlalchemy import inspect

from utils.database import is_postgresql

# revision identifiers, used by Alembic.
revision = "0101_virtual_collection_roms"
down_revision = "0100_roms_facets_table"
branch_labels = None
depends_on = None


TABLE = "virtual_collection_roms"
NAME_MAX_LENGTH = 400

# (collection type, generated column holding its values)
COLLECTION_TYPES = [
    ("genre", "generated_genres"),
    ("franchise", "generated_franchises"),
    ("collection", "generated_collections"),
    ("mode", "generated_game_modes"),
    ("company", "generated_companies"),
]

_COLUMNS = "rom_id, type, name, path_cover_s, path_cover_l, created_at, updated_at"


# ---------------------------------------------------------------------------
# Row-producing SELECTs, shared by the backfill and the triggers
# ---------------------------------------------------------------------------


def _mysql_rows(row: str, from_roms: bool) -> str:
    """Membership rows for one rom (``NEW.``) or for every rom (``r.``)."""
    branches = []
    for type_, column in COLLECTION_TYPES:
        json_table = (
            f"JSON_TABLE({row}.{column}, '$[*]' COLUMNS (value TEXT PATH '$')) j"
        )
        source = f"roms r CROSS JOIN {json_table}" if from_roms else json_table
        branches.append(
            f"SELECT DISTINCT {row}.id, '{type_}', LEFT(j.value, {NAME_MAX_LENGTH}), "  # nosec B608
            f"{row}.path_cover_s, {row}.path_cover_l, NOW(), NOW()\n"
            f"FROM {source}\n"
            f"WHERE j.value IS NOT NULL AND j.value != ''"
        )
    return "\nUNION ALL\n".join(branches)


def _postgres_rows(row: str, from_roms: bool) -> str:
    branches = []
    for type_, column in COLLECTION_TYPES:
        # A provider could store a non-array under the key; unnesting that would
        # raise and abort the rom write, so anything else is read as empty.
        array = (
            f"CASE WHEN jsonb_typeof({row}.{column}) = 'array' "
            f"THEN {row}.{column} ELSE '[]'::jsonb END"
        )
        elements = f"jsonb_array_elements_text({array}) AS j(value)"
        source = f"roms r CROSS JOIN LATERAL {elements}" if from_roms else elements
        branches.append(
            f"SELECT DISTINCT {row}.id, '{type_}', LEFT(j.value, {NAME_MAX_LENGTH}), "  # nosec B608
            f"{row}.path_cover_s, {row}.path_cover_l, NOW(), NOW()\n"
            f"FROM {source}\n"
            f"WHERE j.value IS NOT NULL AND j.value != ''"
        )
    return "\nUNION ALL\n".join(branches)


# ---------------------------------------------------------------------------
# Triggers
# ---------------------------------------------------------------------------

_TRACKED_COLUMNS = [column for _, column in COLLECTION_TYPES] + [
    "path_cover_s",
    "path_cover_l",
]


def _mysql_triggers() -> list[str]:
    insert = f"INSERT IGNORE INTO {TABLE} ({_COLUMNS})\n{_mysql_rows('NEW', False)}"
    unchanged = " AND ".join(f"NEW.{c} <=> OLD.{c}" for c in _TRACKED_COLUMNS)
    return [
        f"CREATE TRIGGER virtual_collection_roms_ai AFTER INSERT ON roms\n"  # nosec B608
        f"FOR EACH ROW\n{insert}",
        f"CREATE TRIGGER virtual_collection_roms_au AFTER UPDATE ON roms\n"  # nosec B608
        f"FOR EACH ROW\nBEGIN\n"
        f"IF NOT ({unchanged}) THEN\n"
        f"DELETE FROM {TABLE} WHERE rom_id = NEW.id;\n"
        f"{insert};\n"
        f"END IF;\n"
        f"END",
    ]


def _postgres_trigger_function() -> str:
    unchanged = " AND ".join(
        f"NEW.{c} IS NOT DISTINCT FROM OLD.{c}" for c in _TRACKED_COLUMNS
    )
    return f"""
CREATE OR REPLACE FUNCTION romm_sync_virtual_collection_roms() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF {unchanged} THEN
            RETURN NULL;
        END IF;
        DELETE FROM {TABLE} WHERE rom_id = NEW.id;
    END IF;

    INSERT INTO {TABLE} ({_COLUMNS})
    {_postgres_rows("NEW", False)}
    ON CONFLICT DO NOTHING;

    RETURN NULL;
END $$
"""  # nosec B608


# ---------------------------------------------------------------------------
# View
# ---------------------------------------------------------------------------

_MYSQL_VIEW = f"""
CREATE VIEW virtual_collections AS
SELECT
    name,
    type,
    CONCAT('Autogenerated ', name, ' collection') COLLATE utf8mb4_general_ci AS description,
    NOW() AS created_at,
    NOW() AS updated_at,
    JSON_ARRAYAGG(rom_id) AS rom_ids
FROM {TABLE}
GROUP BY type, name
HAVING COUNT(DISTINCT rom_id) > 2
"""  # nosec B608

_POSTGRES_VIEW = f"""
CREATE VIEW virtual_collections AS
SELECT
    name,
    type,
    'Autogenerated ' || name || ' collection' AS description,
    NOW() AS created_at,
    NOW() AS updated_at,
    jsonb_agg(rom_id) AS rom_ids
FROM {TABLE}
GROUP BY type, name
HAVING COUNT(DISTINCT rom_id) > 2
"""  # nosec B608


def upgrade() -> None:
    connection = op.get_bind()
    pg = is_postgresql(connection)

    # Every step is guarded so a re-run after a partial failure recovers cleanly.
    # MySQL/MariaDB auto-commit each DDL statement, so a crash mid-migration
    # leaves objects behind without advancing the alembic version.
    collation = None if pg else "utf8mb4_general_ci"
    op.create_table(
        TABLE,
        sa.Column("type", sa.String(length=50, collation=collation), nullable=False),
        sa.Column(
            "name",
            sa.String(length=NAME_MAX_LENGTH, collation=collation),
            nullable=False,
        ),
        sa.Column("rom_id", sa.Integer(), nullable=False),
        sa.Column("path_cover_s", sa.Text(), nullable=True),
        sa.Column("path_cover_l", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["rom_id"], ["roms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("type", "name", "rom_id"),
        if_not_exists=True,
    )

    # MySQL has no CREATE INDEX IF NOT EXISTS, so check the catalog instead.
    index_name = f"idx_{TABLE}_rom_id"
    existing_indexes = {
        index["name"] for index in inspect(connection).get_indexes(TABLE)
    }
    if index_name not in existing_indexes:
        op.create_index(index_name, TABLE, ["rom_id"])

    # The upsert semantics (INSERT IGNORE / ON CONFLICT DO NOTHING) keep the
    # backfill idempotent so a re-run only fills the rows still missing.
    if pg:
        op.execute(  # nosec B608
            f"INSERT INTO {TABLE} ({_COLUMNS})\n"
            f"{_postgres_rows('r', True)}\nON CONFLICT DO NOTHING"
        )
    else:
        op.execute(  # nosec B608
            f"INSERT IGNORE INTO {TABLE} ({_COLUMNS})\n{_mysql_rows('r', True)}"
        )

    if pg:
        op.execute(_postgres_trigger_function())
        op.execute("DROP TRIGGER IF EXISTS virtual_collection_roms_aiu ON roms")
        op.execute(
            "CREATE TRIGGER virtual_collection_roms_aiu AFTER INSERT OR UPDATE ON roms\n"
            "FOR EACH ROW EXECUTE FUNCTION romm_sync_virtual_collection_roms()"
        )
    else:
        op.execute("DROP TRIGGER IF EXISTS virtual_collection_roms_ai")
        op.execute("DROP TRIGGER IF EXISTS virtual_collection_roms_au")
        for trigger in _mysql_triggers():
            op.execute(trigger)

    op.execute("DROP VIEW IF EXISTS virtual_collections")
    op.execute(_POSTGRES_VIEW if pg else _MYSQL_VIEW)


def downgrade() -> None:
    connection = op.get_bind()
    pg = is_postgresql(connection)

    op.execute("DROP VIEW IF EXISTS virtual_collections")
    op.execute(_POSTGRES_LEGACY_VIEW if pg else _MYSQL_LEGACY_VIEW)

    if pg:
        op.execute("DROP TRIGGER IF EXISTS virtual_collection_roms_aiu ON roms")
        op.execute("DROP FUNCTION IF EXISTS romm_sync_virtual_collection_roms()")
    else:
        op.execute("DROP TRIGGER IF EXISTS virtual_collection_roms_ai")
        op.execute("DROP TRIGGER IF EXISTS virtual_collection_roms_au")

    # The rom_id index backs the foreign key, so it goes with the table.
    op.drop_table(TABLE)


# ---------------------------------------------------------------------------
# Derive-on-read view definitions (verbatim from 0095/0096), used only by
# downgrade() to restore the pre-0100 behavior.
# ---------------------------------------------------------------------------

_POSTGRES_LEGACY_VIEW = """
CREATE VIEW virtual_collections AS
WITH base AS (
    SELECT
        r.id as rom_id,
        r.path_cover_s as path_cover_s,
        r.path_cover_l as path_cover_l,
        rm.genres as genres,
        rm.franchises as franchises,
        rm.collections as collections,
        rm.game_modes as game_modes,
        rm.companies as companies
    FROM roms r
    JOIN roms_metadata rm ON rm.rom_id = r.id
),
genres_collection AS (
    SELECT
        rom_id,
        path_cover_s,
        path_cover_l,
        jsonb_array_elements_text(genres) as collection_name,
        'genre' as collection_type
    FROM base
),
franchises_collection AS (
    SELECT
        rom_id,
        path_cover_s,
        path_cover_l,
        jsonb_array_elements_text(franchises) as collection_name,
        'franchise' as collection_type
    FROM base
),
collection_collection AS (
    SELECT
        rom_id,
        path_cover_s,
        path_cover_l,
        jsonb_array_elements_text(collections) as collection_name,
        'collection' as collection_type
    FROM base
),
modes_collection AS (
    SELECT
        rom_id,
        path_cover_s,
        path_cover_l,
        jsonb_array_elements_text(game_modes) as collection_name,
        'mode' as collection_type
    FROM base
),
companies_collection AS (
    SELECT
        rom_id,
        path_cover_s,
        path_cover_l,
        jsonb_array_elements_text(companies) as collection_name,
        'company' as collection_type
    FROM base
)
SELECT
    collection_name as name,
    collection_type as type,
    'Autogenerated ' || collection_type || ' collection' AS description,
    NOW() AS created_at,
    NOW() AS updated_at,
    jsonb_agg(rom_id) as rom_ids,
    jsonb_agg(path_cover_s) as path_covers_s,
    jsonb_agg(path_cover_l) as path_covers_l
FROM (
    SELECT * FROM genres_collection
    UNION ALL
    SELECT * FROM franchises_collection
    UNION ALL
    SELECT * FROM collection_collection
    UNION ALL
    SELECT * FROM modes_collection
    UNION ALL
    SELECT * FROM companies_collection
) combined
GROUP BY collection_type, collection_name
HAVING COUNT(DISTINCT rom_id) > 2
ORDER BY collection_type, collection_name
"""

_MYSQL_LEGACY_VIEW = """
CREATE VIEW virtual_collections AS
WITH base AS (
    SELECT
        r.id as rom_id,
        r.path_cover_s as path_cover_s,
        r.path_cover_l as path_cover_l,
        rm.genres as genres,
        rm.franchises as franchises,
        rm.collections as collections,
        rm.game_modes as game_modes,
        rm.companies as companies
    FROM
        roms r
        JOIN roms_metadata rm ON rm.rom_id = r.id
),
genres AS (
    SELECT
        base.rom_id as rom_id,
        base.path_cover_s as path_cover_s,
        base.path_cover_l as path_cover_l,
        CONCAT(j.genre) COLLATE utf8mb4_general_ci as collection_name,
        'genre' COLLATE utf8mb4_general_ci as collection_type
    FROM
        base
        CROSS JOIN JSON_TABLE(
            base.genres,
            '$[*]' COLUMNS (genre VARCHAR(255) PATH '$')
        ) j
),
franchises AS (
    SELECT
        base.rom_id as rom_id,
        base.path_cover_s as path_cover_s,
        base.path_cover_l as path_cover_l,
        CONCAT(j.franchise) COLLATE utf8mb4_general_ci as collection_name,
        'franchise' COLLATE utf8mb4_general_ci as collection_type
    FROM
        base
        CROSS JOIN JSON_TABLE(
            base.franchises,
            '$[*]' COLUMNS (franchise VARCHAR(255) PATH '$')
        ) j
),
collections AS (
    SELECT
        base.rom_id as rom_id,
        base.path_cover_s as path_cover_s,
        base.path_cover_l as path_cover_l,
        CONCAT(j.collection) COLLATE utf8mb4_general_ci as collection_name,
        'collection' COLLATE utf8mb4_general_ci as collection_type
    FROM
        base
        CROSS JOIN JSON_TABLE(
            base.collections,
            '$[*]' COLUMNS (collection VARCHAR(255) PATH '$')
        ) j
),
modes AS (
    SELECT
        base.rom_id as rom_id,
        base.path_cover_s as path_cover_s,
        base.path_cover_l as path_cover_l,
        CONCAT(j.mode) COLLATE utf8mb4_general_ci as collection_name,
        'mode' COLLATE utf8mb4_general_ci as collection_type
    FROM
        base
        CROSS JOIN JSON_TABLE(
            base.game_modes,
            '$[*]' COLUMNS (mode VARCHAR(255) PATH '$')
        ) j
),
companies AS (
    SELECT
        base.rom_id as rom_id,
        base.path_cover_s as path_cover_s,
        base.path_cover_l as path_cover_l,
        CONCAT(j.company) COLLATE utf8mb4_general_ci as collection_name,
        'company' COLLATE utf8mb4_general_ci as collection_type
    FROM
        base
        CROSS JOIN JSON_TABLE(
            base.companies,
            '$[*]' COLUMNS (company VARCHAR(255) PATH '$')
        ) j
)
SELECT
    collection_name as name,
    collection_type as type,
    CONCAT('Autogenerated ', collection_name, ' collection') COLLATE utf8mb4_general_ci AS description,
    NOW() AS created_at,
    NOW() AS updated_at,
    JSON_ARRAYAGG(rom_id) as rom_ids,
    JSON_ARRAYAGG(path_cover_s) as path_covers_s,
    JSON_ARRAYAGG(path_cover_l) as path_covers_l
FROM
(
    SELECT * FROM genres
    UNION ALL
    SELECT * FROM franchises
    UNION ALL
    SELECT * FROM collections
    UNION ALL
    SELECT * FROM modes
    UNION ALL
    SELECT * FROM companies
) combined
GROUP BY collection_type, collection_name
HAVING COUNT(DISTINCT rom_id) > 2
ORDER BY collection_type, collection_name
"""
