"""update to 1.8.1

Revision ID: 1.8.1
Revises: 1.8
Create Date: 2023-04-17 12:03:19.163501

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1.8.1"
down_revision = "1.8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roms") as batch_op:
        batch_op.add_column(
            sa.Column(
                "url_screenshots",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("(JSON_ARRAY())"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "path_screenshots",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("(JSON_ARRAY())"),
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roms") as batch_op:
        batch_op.drop_column("url_screenshots")
        batch_op.drop_column("path_screenshots")
    # ### end Alembic commands ###
