"""empty message

Revision ID: 1.9.2
Revises: 1.8.3
Create Date: 2023-08-09 21:56:50.289585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1.9.2"
down_revision = "1.8.3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("disabled", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    with op.batch_alter_table("platforms", schema=None) as batch_op:
        batch_op.alter_column(
            "slug", existing_type=mysql.VARCHAR(length=50), nullable=True
        )

    with op.batch_alter_table("roms", schema=None) as batch_op:
        batch_op.alter_column(
            "p_slug", existing_type=mysql.VARCHAR(length=50), nullable=True
        )
        batch_op.alter_column(
            "file_name_no_tags", existing_type=mysql.VARCHAR(length=450), nullable=True
        )
        batch_op.alter_column(
            "url_screenshots",
            existing_type=mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            nullable=True,
            existing_server_default=sa.text("'[]'"),
        )
        batch_op.alter_column(
            "path_screenshots",
            existing_type=mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            nullable=True,
            existing_server_default=sa.text("'[]'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roms", schema=None) as batch_op:
        batch_op.alter_column(
            "path_screenshots",
            existing_type=mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            nullable=False,
            existing_server_default=sa.text("'[]'"),
        )
        batch_op.alter_column(
            "url_screenshots",
            existing_type=mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            nullable=False,
            existing_server_default=sa.text("'[]'"),
        )
        batch_op.alter_column(
            "file_name_no_tags", existing_type=mysql.VARCHAR(length=450), nullable=False
        )
        batch_op.alter_column(
            "p_slug", existing_type=mysql.VARCHAR(length=50), nullable=False
        )

    with op.batch_alter_table("platforms", schema=None) as batch_op:
        batch_op.alter_column(
            "slug", existing_type=mysql.VARCHAR(length=50), nullable=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    # ### end Alembic commands ###
