from typing import NotRequired, TypedDict

from config import HASHEOUS_API_ENABLED

from .base_handler import MetadataHandler
from .base_handler import UniversalPlatformSlug as UPS


class GiantBombPlatform(TypedDict):
    slug: str
    giantbomb_id: int | None
    giantbomb_slug: NotRequired[str]
    name: NotRequired[str]
    description: NotRequired[str]
    url: NotRequired[str]
    url_logo: NotRequired[str]


#     {
#       "deck": "A top-down isometric helicopter shoot 'em up originally for the Sega Genesis, which was later ported to a variety of platforms. It is best known for its open-ended mission design and was followed by several sequels.",
#       "description": "<h2>Overview</h2><p>Desert Strike: Return to the Gulf is an isometric helicopter shoot 'em up from Electronic Arts. The player is a fighter pilot who must take down mission-critical targets across a number of maps. The player is free to pursue these missions in any order, and must also keep an eye on the fuel, damage, and ammo gauges.</p><p>Desert Strike is the first of the prolific <a href=\"/strike-series/3025-143/\" data-ref-id=\"3025-143\">Strike</a> series, and was followed with <a href=\"/jungle-strike/3030-2180/\" data-ref-id=\"3030-2180\">Jungle Strike</a> and <a href=\"/urban-strike/3030-9336/\" data-ref-id=\"3030-9336\">Urban Strike</a> on the Genesis. Two more games, <a href=\"/soviet-strike/3030-2422/\" data-ref-id=\"3030-2422\">Soviet Strike</a> and <a href=\"/nuclear-strike/3030-11731/\" data-ref-id=\"3030-11731\">Nuclear Strike</a>, were released later for 32-bit systems.</p><h2>Story</h2><p>A year after the Gulf War, General Ibn Kilbaba takes over a small <a href=\"/unnamed-middle-eastern-location/3035-179/\" data-ref-id=\"3035-179\">Arab emirate</a> and plans to start World War III. Using an <a href=\"/ah-64-apache/3055-2463/\" data-ref-id=\"3055-2463\">AH-64 Apache</a>, the player must open the way for ground troops and finally take on the \"Madman\" himself.</p><h2>Gameplay</h2><p>The game is played from an isometric perspective in open levels that allow free movement in all directions by scrolling the screen with the movement of the helicopter. Each level consists of many varying objectives that range anywhere from destroying enemy bases and vehicles to capturing enemy troops or rescuing friendly ones. While bases and vehicles are simply destroyed, both friendly and enemy troops must be taken back to base for extraction. The AH-64 Apache has limited cargo space, so multiple trips to and from the base may be necessary. These objectives aren't always linear, and can often be tackled in whatever order the player chooses. This combination of free movement and non-linear structure separated Desert Strike from many of the other contemporary shooters.</p><p>There are three weapons of varying strength and usefulness available to the AH-64 Apache: machine guns, hydra missiles, and hellfire missiles, which increase in strength respectively. Each of these weapons has a limited number of ammo which can only be replenished by picking up ammo crates on the mission or by resupplying back at the base. Similarly, the AH-64 Apache only has a limited amount of fuel that will drain slowly over the course of each level. If the fuel runs out, the helicopter crashes and the player loses a life. Refueling works exactly the same as restocking ammo.</p><p>Lives are lost when either the AH-64 Apache takes too much damage and is destroyed, or when it runs out of fuel. After three lives have been lost, the game is over. Due to the nature of the game's freedom, each level requires a certain amount of planning and strategy in order to complete all of the objectives while still having enough fuel, ammo, and health to survive.</p><h2>Ports</h2><p>Due to its popularity on the <a href=\"/sega-genesis/3055-4659/\" data-ref-id=\"3055-4659\">Sega Genesis</a> in 1992, the game was then ported to the <a href=\"/amiga/3045-1/\" data-ref-id=\"3045-1\">Amiga</a>, <a href=\"/sega-master-system/3045-8/\" data-ref-id=\"3045-8\">Master System</a>, and <a href=\"/snes/3045-9/\" data-ref-id=\"3045-9\">SNES</a> in the same year. Two years later in 1994, it was released on the <a href=\"/pc/3045-94/\" data-ref-id=\"3045-94\">PC</a>. It was also ported to most handheld systems such as the <a href=\"/lynx/3045-7/\" data-ref-id=\"3045-7\">Lynx</a> in 1993, <a href=\"/game-gear/3045-5/\" data-ref-id=\"3045-5\">Game Gear</a> in 1994, <a href=\"/game-boy/3045-3/\" data-ref-id=\"3045-3\">Game Boy</a> in 1995, <a href=\"/game-boy-advance/3045-4/\" data-ref-id=\"3045-4\">Game Boy Advance</a> in 2002, and finally the <a href=\"/psp/3045-18/\" data-ref-id=\"3045-18\">PSP</a> in 2006 as part of <a href=\"/ea-replay/3030-10965/\" data-ref-id=\"3030-10965\">EA Replay</a>.</p>",
#       "expected_release_year": "1992",
#       "guid": "3030-1",
#       "id": 1,
#       "image": {
#         "icon_url": "/api/v1/MetadataProxy/GiantBomb/a/uploads/square_avatar/9/93770/2370498-genesis_desertstrike_2__1_.jpg",
#         "medium_url": "/api/v1/MetadataProxy/GiantBomb/a/uploads/scale_medium/9/93770/2370498-genesis_desertstrike_2__1_.jpg",
#         "screen_url": "/api/v1/MetadataProxy/GiantBomb/a/uploads/screen_medium/9/93770/2370498-genesis_desertstrike_2__1_.jpg",
#         "screen_large_url": "/api/v1/MetadataProxy/GiantBomb/a/uploads/screen_kubrick/9/93770/2370498-genesis_desertstrike_2__1_.jpg",
#         "small_url": "/api/v1/MetadataProxy/GiantBomb/a/uploads/scale_small/9/93770/2370498-genesis_desertstrike_2__1_.jpg",
#         "super_url": "/api/v1/MetadataProxy/GiantBomb/a/uploads/scale_large/9/93770/2370498-genesis_desertstrike_2__1_.jpg",
#         "thumb_url": "/api/v1/MetadataProxy/GiantBomb/a/uploads/scale_avatar/9/93770/2370498-genesis_desertstrike_2__1_.jpg",
#         "tiny_url": "/api/v1/MetadataProxy/GiantBomb/a/uploads/square_mini/9/93770/2370498-genesis_desertstrike_2__1_.jpg",
#         "original_url": "/api/v1/MetadataProxy/GiantBomb/a/uploads/original/9/93770/2370498-genesis_desertstrike_2__1_.jpg"
#       },
#       "name": "Desert Strike: Return to the Gulf",
#       "number_of_user_reviews": "0",
#       "original_game_rating": [
#         {
#           "api_detail_url": "https://www.giantbomb.com/api/game_rating/3065-9/",
#           "id": 9,
#           "name": "ESRB: K-A"
#         },
#         {
#           "api_detail_url": "https://www.giantbomb.com/api/game_rating/3065-6/",
#           "id": 6,
#           "name": "ESRB: E"
#         }
#       ],
#       "site_detail_url": "https://www.giantbomb.com/desert-strike-return-to-the-gulf/3030-1/"
#     }


class GiantBombMetadata(TypedDict):
    guid: str
    alternative_names: list[str]
    deck: str
    description: str
    first_release_date: str
    image: dict
    age_ratings: list[str]
    site_url: str


class GiantBombHandler(MetadataHandler):
    """Handler for Giant Bomb metadata."""

    def __init__(self) -> None:
        pass

    @classmethod
    def is_enabled(cls) -> bool:
        """Return whether this metadata handler is enabled."""
        return HASHEOUS_API_ENABLED

    def get_platform(self, slug: str) -> GiantBombPlatform:
        if slug not in GIANTBOMB_PLATFORM_LIST:
            return GiantBombPlatform(giantbomb_id=None, slug=slug)

        platform = GIANTBOMB_PLATFORM_LIST[UPS(slug)]

        return GiantBombPlatform(
            slug=slug,
            giantbomb_id=platform["id"],
            giantbomb_slug=platform["slug"],
            name=platform["title"],
            description=platform["description"],
            url=platform["url"],
            url_logo=platform["url_logo"],
        )


class SlugToGiantBombPlatform(TypedDict):
    id: int
    slug: str
    title: str
    description: str
    url: str
    url_logo: str


GIANTBOMB_PLATFORM_LIST: dict[UPS, SlugToGiantBombPlatform] = {
    UPS._3DO: {
        "id": 26,
        "slug": "3do",
        "title": "3DO",
        "description": "3DO was a video game console manufactured by Panasonic, Goldstar, and Sanyo. Despite the initial hype surrounding the system, the console's $700 price tag proved to be the ultimate kiss of death for the system.",
        "url": "https://www.giantbomb.com/3do/3045-26/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/1/12419/254585-3do_fz1.jpg",
    },
    UPS.N3DS: {
        "id": 117,
        "slug": "nintendo-3ds",
        "title": "Nintendo 3DS",
        "description": "The Nintendo 3DS is a portable game console produced by Nintendo. The handheld features stereoscopic 3D technology that doesn't require glasses. It was released in Japan on February 26, 2011 and in North America on March 27, 2011.",
        "url": "https://www.giantbomb.com/nintendo-3ds/3045-117/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/5150/1686079-3dshw11911.jpg",
    },
    UPS.N64DD: {
        "id": 101,
        "slug": "nintendo-64dd",
        "title": "Nintendo 64DD",
        "description": "The Nintendo 64 Disk Drive was an expansion for the Nintendo 64 allowing the use of magnetic disks that offered greater storage capacity and the ability to be written to.",
        "url": "https://www.giantbomb.com/nintendo-64dd/3045-101/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/9566/394176-n64_disc_drive.jpg",
    },
    UPS.ABC_80: {
        "id": 170,
        "slug": "luxor-abc80",
        "title": "Luxor ABC 80",
        "description": "The Advanced BASIC Computer line was created in 1978 with the release of the ABC 80, a joint venture between Luxor AB, DIAB and Scandia Metric.",
        "url": "https://www.giantbomb.com/luxor-abc80/3045-170/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/2975830-1340529857-Luxor.jpg",
    },
    UPS.ACORN_ARCHIMEDES: {
        "id": 125,
        "slug": "acorn-archimedes",
        "title": "Acorn Archimedes",
        "description": "The Acorn Archimedes was a range of personal computers from Acorn Computers aimed at both educational and home use. It featured a 32-bit ARM processor and the RISC OS operating system.",
        "url": "https://www.giantbomb.com/acorn-archimedes/3045-125/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/1529461-acorna30002.jpg",
    },
    UPS.ACPC: {
        "id": 11,
        "slug": "amstrad-cpc",
        "title": "Amstrad CPC",
        "description": "The Amstrad CPC (Colour Personal Computer) was a series of 8-bit personal computers developed by Amstrad between 1984 and 1990. During its lifetime, approximately 3 million CPCs were sold.",
        "url": "https://www.giantbomb.com/amstrad-cpc/3045-11/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10073-Amstrad_CPC464.jpg",
    },
    UPS.ACTION_MAX: {
        "id": 148,
        "slug": "action-max",
        "title": "Action Max",
        "description": "Worlds of Wonder created this VCR-based console in 1987.",
        "url": "https://www.giantbomb.com/action-max/3045-148/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954575-action-max-set-fl.jpg",
    },
    UPS.ADVANCED_PICO_BEENA: {
        "id": 174,
        "slug": "advanced-pico-beena",
        "title": "Advanced Pico Beena",
        "description": "SegaToys launched this successor to the kid-focused Pico console in 2005. A lower-priced model called the BeenaLite followed in 2008, but neither was released outside Japan.",
        "url": "https://www.giantbomb.com/advanced-pico-beena/3045-174/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/3061845-8449526446-Advan.jpg",
    },
    UPS.ADVENTURE_VISION: {
        "id": 93,
        "slug": "adventure-vision",
        "title": "Adventure Vision",
        "description": "The Adventure Vision is a handheld video game console developed by Entex Industries in 1982.",
        "url": "https://www.giantbomb.com/adventure-vision/3045-93/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/46/1248213-adventurevision.jpg",
    },
    UPS.AMAZON_ALEXA: {
        "id": 172,
        "slug": "amazon-alexa",
        "title": "Amazon Alexa",
        "description": "Amazon Alexa is a virtual assistant that reacts to voice commands.",
        "url": "https://www.giantbomb.com/amazon-alexa/3045-172/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3028557-51tfnr7atgl._sy300_ql70_.jpg",
    },
    UPS.AMAZON_FIRE_TV: {
        "id": 158,
        "slug": "amazon-fire-tv",
        "title": "Amazon Fire TV",
        "description": "Amazon Fire TV is a streaming device that allows users to stream content from the internet to their TV.",
        "url": "https://www.giantbomb.com/amazon-fire-tv/3045-158/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/3276566-0122928757-0-599.jpg",
    },
    UPS.AMIGA: {
        "id": 1,
        "slug": "amiga",
        "title": "Amiga",
        "description": "The Amiga was a personal computer from Commodore that was released in a variety of different configurations.",
        "url": "https://www.giantbomb.com/amiga/3045-1/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10069-a500_plus1.jpg",
    },
    UPS.AMIGA_CD32: {
        "id": 39,
        "slug": "amiga-cd32",
        "title": "Amiga CD32",
        "description": "The Amiga CD32 was Commodore's attempt at a gaming console and what turned out to be their swan song. The majority of its library were upgraded Amiga games.",
        "url": "https://www.giantbomb.com/amiga-cd32/3045-39/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10070-cd32.jpg",
    },
    UPS.AMSTRAD_PCW: {
        "id": 197,
        "slug": "amstrad-pcw",
        "title": "Amstrad PCW",
        "description": "Amstrad's PCW was primarily built as a word processor that was cheaper than the other computers offered at the time. Some games were also made available for the platform.",
        "url": "https://www.giantbomb.com/amstrad-pcw/3045-197/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/3235400-9113310639-Amstr.jpg",
    },
    UPS.ANDROID: {
        "id": 123,
        "slug": "android",
        "title": "Android",
        "description": "Google's mobile OS, available across multiple devices.",
        "url": "https://www.giantbomb.com/android/3045-123/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/1465136-android_robot_logo.jpg",
    },
    UPS.APF: {
        "id": 190,
        "slug": "apf-mp-1000",
        "title": "APF MP-1000",
        "description": "The APF MP-1000 is an 8-bit console released by APF Electronics in 1978.",
        "url": "https://www.giantbomb.com/apf-mp-1000/3045-190/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3195621-c9bef87c3a182a89d06bdde5a5dfc081.jpg",
    },
    UPS.APPLE_IIGS: {
        "id": 38,
        "slug": "apple-iigs",
        "title": "Apple IIgs",
        "description": 'The Apple ][gs - which stood for "Graphics and Sound" - was Apple\'s upgraded version of the popular Apple ][ line of computers.  The system was capable of playing standard Apple ][ games, as well as games made specifically for the GS.',
        "url": "https://www.giantbomb.com/apple-iigs/3045-38/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10075-appleiigs.jpg",
    },
    UPS.APPLEII: {
        "id": 12,
        "slug": "apple-ii",
        "title": "Apple II",
        "description": "The Apple II was a line of personal computers produced by Apple Computer, Inc. from 1977 to 1993.",
        "url": "https://www.giantbomb.com/apple-ii/3045-12/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10074-apple_ii_large.jpg",
    },
    UPS.AQUARIUS: {
        "id": 100,
        "slug": "aquarius",
        "title": "Aquarius",
        "description": "Aquarius is a home computer made by Mattel.  Released in June 1983, it was discontinued only a few months later in October 1983.\n\n",
        "url": "https://www.giantbomb.com/aquarius/3045-100/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/46/187822-aquarius.jpg",
    },
    UPS.ARCADE: {
        "id": 84,
        "slug": "arcade",
        "title": "Arcade",
        "description": "Stand-alone machines specialized for individual games. Arcades began the game industry and peaked in popularity before home consoles took over the gaming public. Arcade games usually cost 25 cents, or 100 yen, per play. Known for the most cutting-edge technology of their time, arcades have the largest video game library, and greatest variety of control methods, of any platform.",
        "url": "https://www.giantbomb.com/arcade/3045-84/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/9566/401036-mame_arcade_essential_cabinet.jpg",
    },
    UPS.ARCADIA_2001: {
        "id": 99,
        "slug": "arcadia-2001",
        "title": "Arcadia 2001",
        "description": "Arcadia 2001 is an 8-bit console made by Emerson.",
        "url": "https://www.giantbomb.com/arcadia-2001/3045-99/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/46/187197-arcadia2001.gif",
    },
    UPS.ASTROCADE: {
        "id": 120,
        "slug": "bally-astrocade",
        "title": "Bally Astrocade",
        "description": "The Astrocade is a cartridge-based video game system that competed directly with the Atari 2600 in the late 1970s.",
        "url": "https://www.giantbomb.com/bally-astrocade/3045-120/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/1322955-ballystm.jpg",
    },
    UPS.JAGUAR_CD: {
        "id": 171,
        "slug": "jaguar-cd",
        "title": "Jaguar CD",
        "description": "Atari released a CD-ROM drive for the Jaguar on September 21, 1995 for $149.99.",
        "url": "https://www.giantbomb.com/jaguar-cd/3045-171/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/2988687-atari_jaguar_cd_retropixl_retrogaming_retro_gaming_2.png",
    },
    UPS.ATARI_ST: {
        "id": 13,
        "slug": "atari-st",
        "title": "Atari ST",
        "description": "Atari's 16-bit computer line was one of the most popular computers in the mid-1980s to early 1990s.",
        "url": "https://www.giantbomb.com/atari-st/3045-13/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/5258/220119-atari_1040stf.jpg",
    },
    UPS.ATARI_VCS: {
        "id": 202,
        "slug": "atari-vcs",
        "title": "Atari VCS",
        "description": 'The Atari VCS is billed as a "PC/Console Hybrid," with the console side having its own online storefront and a selection of games and apps.',
        "url": "https://www.giantbomb.com/atari-vcs/3045-202/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/3302676-atarivcs2019.jpg",
    },
    UPS.ATARI2600: {
        "id": 40,
        "slug": "atari-2600",
        "title": "Atari 2600",
        "description": "The Atari 2600 is one of the first home game consoles, and one of the most successful at the time. Though it could be seen as the Grandfather of Consoles, it was also nearly the Grim Reaper, contributing to the industry collapse years later.",
        "url": "https://www.giantbomb.com/atari-2600/3045-40/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10066-atari2600.jpg",
    },
    UPS.ATARI5200: {
        "id": 67,
        "slug": "atari-5200",
        "title": "Atari 5200",
        "description": "The Atari 5200 Supersystem was released in 1982, as a followup to the successful VCS/Atari 2600.",
        "url": "https://www.giantbomb.com/atari-5200/3045-67/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10083-5200.jpg",
    },
    UPS.ATARI7800: {
        "id": 70,
        "slug": "atari-7800",
        "title": "Atari 7800",
        "description": "The third console released by Atari, and successor to the Atari 5200. It features backwards compatibility with the Atari 2600.",
        "url": "https://www.giantbomb.com/atari-7800/3045-70/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10088-7800.gif",
    },
    UPS.ATARI8BIT: {
        "id": 24,
        "slug": "atari-8-bit",
        "title": "Atari 8-bit",
        "description": "A line of 8-bit computers produced by Atari, Inc. from 1979 to 1992.",
        "url": "https://www.giantbomb.com/atari-8-bit/3045-24/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10170-Atari-800.jpg",
    },
    UPS.BBCMICRO: {
        "id": 110,
        "slug": "bbc-micro",
        "title": "BBC Micro",
        "description": "Designed and built by Acorn Computers in 1981 as part of the BBC's Computer Literacy Project, the BBC Microcomputer System was notable for its rugged build quality, expandability and feature set. Several notable British developers started out making games for this system.",
        "url": "https://www.giantbomb.com/bbc-micro/3045-110/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/5028/1738077-bbc_micro_owl.png",
    },
    UPS.BROWSER: {
        "id": 140,
        "slug": "browser",
        "title": "Browser",
        "description": "Browser-based games are typically platform-independent pieces of software that run directly in the same application you use to read this web page.",
        "url": "https://www.giantbomb.com/browser/3045-140/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4231/942780-q20.jpg",
    },
    UPS.C128: {
        "id": 58,
        "slug": "commodore-128",
        "title": "Commodore 128",
        "description": "The Commodore 128 is the successor to the extremely popular Commodore 64 computer. The Commodore 128 is the last 8-bit computer produced by Commodore Business Machines.",
        "url": "https://www.giantbomb.com/commodore-128/3045-58/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954661-4388797273-C5YEu.jpg",
    },
    UPS.C16: {
        "id": 150,
        "slug": "commodore-16",
        "title": "Commodore 16",
        "description": "Commodore's successor to the VIC-20 that never sold well.",
        "url": "https://www.giantbomb.com/commodore-16/3045-150/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/2359950-1280px_commodore_16_002a.png",
    },
    UPS.C64: {
        "id": 14,
        "slug": "commodore-64",
        "title": "Commodore 64",
        "description": "The Commodore 64 personal computer dominated the market from 1983-1985, and stands as one of the best-selling personal computers of all time.",
        "url": "https://www.giantbomb.com/commodore-64/3045-14/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10289-c64.jpg",
    },
    UPS.CASIO_LOOPY: {
        "id": 126,
        "slug": "casio-loopy",
        "title": "Casio Loopy",
        "description": "This Japan-only release was targeted at young girls and featured a built-in thermal printer to allow users to print their own puri-kura-style stickers. Only 10 games were released for the console.",
        "url": "https://www.giantbomb.com/casio-loopy/3045-126/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/1643279-casioloopy.jpg",
    },
    UPS.CASIO_PV_1000: {
        "id": 149,
        "slug": "casio-pv-1000",
        "title": "Casio PV-1000",
        "description": "The Casio PV-1000 was released in Japan in 1983. Only 15 games were produced.",
        "url": "https://www.giantbomb.com/casio-pv-1000/3045-149/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/14/148570/2318191-casio_pv_1000.jpg",
    },
    UPS.CASIO_PV_2000: {
        "id": 187,
        "slug": "casio-pv-2000",
        "title": "Casio PV-2000",
        "description": "The Casio PV-2000 was a gaming computer released by Casio in Japan in 1983. Only eleven games were released in its lifetime, and it is not compatible with Casio PV-1000 games.",
        "url": "https://www.giantbomb.com/casio-pv-2000/3045-187/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3195587-casio_pv2000_1.jpg",
    },
    UPS.COLECOADAM: {
        "id": 207,
        "slug": "coleco-adam",
        "title": "Coleco Adam",
        "description": "The Coleco Adam is a standalone home computer as well as an expansion module released for the ColecoVision in October 1983. Several games were released that required an Adam-compatible devices.",
        "url": "https://www.giantbomb.com/coleco-adam/3045-207/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3376494-8410875235-adam-.jpg",
    },
    UPS.COLECOVISION: {
        "id": 47,
        "slug": "colecovision",
        "title": "ColecoVision",
        "description": "The ColecoVision came out in 1982 and had a successful run as the Atari 5200's competitor until 1984.",
        "url": "https://www.giantbomb.com/colecovision/3045-47/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/1270971-colecovision.jpg",
    },
    UPS.COMMODORE_CDTV: {
        "id": 142,
        "slug": "commodore-cdtv",
        "title": "Commodore CDTV",
        "description": "The CDTV was a repurposed Amiga 500 that focused on multimedia games and applications in the early 1990s.",
        "url": "https://www.giantbomb.com/commodore-cdtv/3045-142/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/10/103881/2017382-cdtv.jpg",
    },
    UPS.CPET: {
        "id": 62,
        "slug": "commodore-petcbm",
        "title": "Commodore PET/CBM",
        "description": "The PET (Personal Electronic Transactor) was a home-/personal computer produced by Commodore starting in 1977.",
        "url": "https://www.giantbomb.com/commodore-petcbm/3045-62/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10320-Commodore_PET4032.jpg",
    },
    UPS.CREATIVISION: {
        "id": 209,
        "slug": "vtech-creativision",
        "title": "VTech CreatiVision",
        "description": "The VTech CreatiVision is a video game console developed by VTech in 1983. It was released in the USA and Canada in 1983 and in Europe in 1984.",
        "url": "https://www.giantbomb.com/vtech-creativision/3045-209/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3341713-images.jpeg",
    },
    UPS.DC: {
        "id": 37,
        "slug": "dreamcast",
        "title": "Dreamcast",
        "description": "The Dreamcast is the fifth and final console developed by Sega. As the first 128-bit system, it was the first to offer truly arcade-quality 3D graphics. It is famous for being the first console to include worldwide online capability, its game library, and its unexpectedly short life span.",
        "url": "https://www.giantbomb.com/dreamcast/3045-37/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/1426199-logo.jpg",
    },
    UPS.DENSHI_MANGAJUKU: {
        "id": 200,
        "slug": "denshi-mangajuku",
        "title": "Denshi Mangajuku",
        "description": "The Denshi Manga (Design Master) was released by Bandai in 1995. It is considered the first touch screen gaming device ever produced.",
        "url": "https://www.giantbomb.com/denshi-mangajuku/3045-200/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3281904-designmastersenshimangajukuun_box.jpg",
    },
    UPS.DIDJ: {
        "id": 144,
        "slug": "leapfrog-didj",
        "title": "Leapfrog Didj",
        "description": "The Leapfrog Didj is a handheld console that was originally released in 2008. It's built for educational software, but runs a Linux distribution that has created a bit of hacker interest.",
        "url": "https://www.giantbomb.com/leapfrog-didj/3045-144/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/14/148570/2203035-didj_custom_gaming_system_product_shot_540x360.jpg",
    },
    UPS.DIGIBLAST: {
        "id": 192,
        "slug": "digiblast",
        "title": "Digiblast",
        "description": "The Digiblast (digiBLAST) is a handheld console produced by Nikko in the Netherlands and released in 2005.",
        "url": "https://www.giantbomb.com/digiblast/3045-192/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3195630-unnamed.jpg",
    },
    UPS.DRAGON_32_SLASH_64: {
        "id": 61,
        "slug": "dragon-3264",
        "title": "Dragon 32/64",
        "description": "The Dragon 32 and Dragon 64 is to date the only computer to be made in Wales, UK.  The companies short history spanned only August 1982 - June 1984.",
        "url": "https://www.giantbomb.com/dragon-3264/3045-61/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10321-dragon64.gif",
    },
    UPS.DVD_PLAYER: {
        "id": 208,
        "slug": "dvd",
        "title": "DVD",
        "description": "While primarily a format for movies and other video, video games were made that are playable via a standard DVD player.",
        "url": "https://www.giantbomb.com/dvd/3045-208/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3377656-screenshot2022-05-30at10.43.03am.png",
    },
    UPS.EPOCH_CASSETTE_VISION: {
        "id": 135,
        "slug": "epoch-cassette-vision",
        "title": "Epoch Cassette Vision",
        "description": "A cartridge-based system released in Japan in 1981.",
        "url": "https://www.giantbomb.com/epoch-cassette-vision/3045-135/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/12/125537/1749867-giant_bomb_sub.jpg",
    },
    UPS.EPOCH_GAME_POCKET_COMPUTER: {
        "id": 182,
        "slug": "epoch-game-pocket-computer",
        "title": "Epoch Game Pocket Computer",
        "description": "The Epoch Game Pocket Computer was released in Japan in 1984. It features a 75x64 resolution LCD screen with two built-in games. Only five other game cartridges were released.",
        "url": "https://www.giantbomb.com/epoch-game-pocket-computer/3045-182/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3185773-screen%20shot%202020-04-24%20at%206.46.42%20pm.png",
    },
    UPS.EPOCH_SUPER_CASSETTE_VISION: {
        "id": 136,
        "slug": "super-cassette-vision",
        "title": "Super Cassette Vision",
        "description": "Epoch's follow-up to the Cassette Vision was released in 1984.",
        "url": "https://www.giantbomb.com/super-cassette-vision/3045-136/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/12/126726/1755684-images.jpeg",
    },
    UPS.EVERCADE: {
        "id": 180,
        "slug": "evercade",
        "title": "Evercade",
        "description": "Evercade is a range of consoles that plays officially licensed cartridge-based collections of retro 8-bit, 16-bit, 32-bit and 64-bit console games, arcade games and 8-bit and 16-bit home computer games.",
        "url": "https://www.giantbomb.com/evercade/3045-180/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3134988-evercade-featured-graphic-with-cart.jpg",
    },
    UPS.FAIRCHILD_CHANNEL_F: {
        "id": 66,
        "slug": "channel-f",
        "title": "Channel F",
        "description": "The Fairchild Video Entertainment System, later called the Fairchild Channel F, was the first video game console to feature a microprocessor, interchangeable game cartridges, and detachable controllers.",
        "url": "https://www.giantbomb.com/channel-f/3045-66/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10174-fairchild%20channel%20f.jpg",
    },
    UPS.FDS: {
        "id": 91,
        "slug": "famicom-disk-system",
        "title": "Famicom Disk System",
        "description": "The Famicom Disk System was an add-on accessory for the Nintendo Entertainment System's Japanese counterpart. With its games coming on a floppy disk-like medium, many of its releases saw conversions to cartridges both overseas and within Japan.",
        "url": "https://www.giantbomb.com/famicom-disk-system/3045-91/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10341-fds.jpg",
    },
    UPS.FM_7: {
        "id": 114,
        "slug": "fm-7",
        "title": "FM-7",
        "description": "The second in Fujitsu's FM line of computers, the FM-7 was intended more for the mass market, and received fair popularity in Japan.",
        "url": "https://www.giantbomb.com/fm-7/3045-114/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4/1151387-fm7ad.jpg",
    },
    UPS.FM_TOWNS: {
        "id": 108,
        "slug": "fm-towns",
        "title": "FM Towns",
        "description": "A proprietary 32-bit computer from Fujitsu, released in 1989 only in Japan. The first computer with a standard CD-ROM drive, it had many CD enhanced versions of Eastern and Western games (including action, adventure and RPG titles) which are sought after to this day by collectors. Its console version, FM Towns Marty, released in 1993 as the first 5th-gen console.",
        "url": "https://www.giantbomb.com/fm-towns/3045-108/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4527/1109993-fmtowns.jpg",
    },
    UPS.GAMATE: {
        "id": 166,
        "slug": "gamate",
        "title": "Gamate",
        "description": 'The Gamate, also known as the "Super Boy" in Taiwan, is a handheld platform originally manufactured in 1990.',
        "url": "https://www.giantbomb.com/gamate/3045-166/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/2917446-gamate_ad.jpg",
    },
    UPS.GAME_DOT_COM: {
        "id": 77,
        "slug": "gamecom",
        "title": "Game.Com",
        "description": "Tiger's second short-lived portable console was a video game and PDA hybrid",
        "url": "https://www.giantbomb.com/gamecom/3045-77/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954597-tiger-game-com-fl.jpg",
    },
    UPS.GAME_WAVE: {
        "id": 105,
        "slug": "game-wave",
        "title": "Game Wave",
        "description": "The Game Wave Family Entertainment System is a simple DVD-based game platform from ZAPiT Games.",
        "url": "https://www.giantbomb.com/game-wave/3045-105/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954589-game-wave-console-set-fl.jpg",
    },
    UPS.GAMEGEAR: {
        "id": 5,
        "slug": "game-gear",
        "title": "Game Gear",
        "description": "Sega's first hand held video game system.  It was the portable version of the Master System.",
        "url": "https://www.giantbomb.com/game-gear/3045-5/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/1426271-logo.jpg",
    },
    UPS.GAMEKING: {
        "id": 188,
        "slug": "timetop-gameking",
        "title": "Timetop GameKing",
        "description": "The Timetop GameKing is a Chinese handheld console. While being a gray-scale, 8-bit system, it was notable for its excellent audio.",
        "url": "https://www.giantbomb.com/timetop-gameking/3045-188/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3195589-cam06453_orig.jpg",
    },
    UPS.GAMEKINGIII: {
        "id": 189,
        "slug": "timetop-gameking-iii",
        "title": "Timetop GameKing III",
        "description": "The Timetop GameKing III is a handheld console release in Asia by Guangzhou Daidaixing Electronics Tech. Unlike previous iterations, the GameKing III features a color screen. It is backwards compatible with GameKing I &amp; II games.",
        "url": "https://www.giantbomb.com/timetop-gameking-iii/3045-189/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3195620-2560px-gameking_iii_%28gm-221%29.jpg",
    },
    UPS.GB: {
        "id": 3,
        "slug": "game-boy",
        "title": "Game Boy",
        "description": "Nintendo's first handheld gaming console was immensely popular among gamers, selling millions. Despite its grayscale color scheme, it still got support from developers and publishers.",
        "url": "https://www.giantbomb.com/game-boy/3045-3/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/1426210-logo.jpg",
    },
    UPS.GBA: {
        "id": 4,
        "slug": "game-boy-advance",
        "title": "Game Boy Advance",
        "description": "The third platform in the Game Boy line, the Game Boy Advance was offered in a multitude of colors and had three hardware offerings, the sideways Game Boy Advance, the flip Game Boy Advance SP and the tiny Game Boy Advance Micro.",
        "url": "https://www.giantbomb.com/game-boy-advance/3045-4/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/2121789-gba.png",
    },
    UPS.GBC: {
        "id": 57,
        "slug": "game-boy-color",
        "title": "Game Boy Color",
        "description": "Nintendo's successor to the Game Boy, featuring a color screen and backwards compatibility for all previous Game Boy titles.",
        "url": "https://www.giantbomb.com/game-boy-color/3045-57/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/1426240-logo.jpg",
    },
    UPS.GENESIS: {
        "id": 6,
        "slug": "genesis",
        "title": "Genesis",
        "description": "After the cult success of their 8-bit Master System, Sega decided to give gamers a taste of their arcade capabilities with a 16-bit console. Known worldwide as the Mega Drive but called Genesis in the US, it provided graphics and sound a couple of steps below their popular System 16 arcade cabinets. The Mega Drive/Genesis turned out to be Sega's most successful console.",
        "url": "https://www.giantbomb.com/genesis/3045-6/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10576-genesis.jpg",
    },
    UPS.GIZMONDO: {
        "id": 78,
        "slug": "gizmondo",
        "title": "Gizmondo",
        "description": "The Gizmondo is a failed handheld console, which launched in 2005. It was potentially revolutionary for having functionality such as GPRS mobile data connection, a camera, GPS, a multimedia player and of course game playing all in one unit.",
        "url": "https://www.giantbomb.com/gizmondo/3045-78/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10602-gizmondo.jpg",
    },
    UPS.GP32: {
        "id": 133,
        "slug": "gamepark-32",
        "title": "GamePark 32",
        "description": "The GamePark 32 is a Korean handheld that actually attained popularity in European markets after its release. The console was popular due to its vast abilities, including emulation, freeware, homebrew, music playback, and more.",
        "url": "https://www.giantbomb.com/gamepark-32/3045-133/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/7465/1749578-gp3201.jpg",
    },
    UPS.HALCYON: {
        "id": 107,
        "slug": "rdi-halcyon",
        "title": "RDI Halcyon",
        "description": "The RDI Halcyon was a short-lived laserdisc-based game platform. Only two games were properly released for the system.  It was the most expensive video game console ever released, retailing at $2,500.",
        "url": "https://www.giantbomb.com/rdi-halcyon/3045-107/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/874497-rdi.jpg",
    },
    UPS.HARTUNG: {
        "id": 158,
        "slug": "game-master",
        "title": "Game Master",
        "description": "The Hartung Game Master is a monochrome handheld gaming machine that was marketed under different names, including the Systema 2000 and Super Game.",
        "url": "https://www.giantbomb.com/game-master/3045-158/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/2780052-hgm.jpg",
    },
    UPS.HITACHI_S1: {
        "id": 198,
        "slug": "hitachi-s1",
        "title": "Hitachi S1",
        "description": 'The Hitachi S1 is a home computer that was primarily sold in Japan, but also in parts of Australia. It used proprietary 5.25" floppy disks.',
        "url": "https://www.giantbomb.com/hitachi-s1/3045-198/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3242271-hitachi-s1-01.jpg",
    },
    UPS.HYPERSCAN: {
        "id": 104,
        "slug": "hyperscan",
        "title": "HyperScan",
        "description": "Mattel's HyperScan allowed players to scan in RFID-equipped cards to bring in new characters, weapons, and powers. It came packaged with X-Men, Spider-Man and Ben 10.",
        "url": "https://www.giantbomb.com/hyperscan/3045-104/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/2681/841197-hyperscan.jpg",
    },
    UPS.INTELLIVISION: {
        "id": 51,
        "slug": "intellivision",
        "title": "Intellivision",
        "description": "The Intellivision by Mattel Electronics was a system known for its unique controllers and cutting-edge graphics in the early 1980s, but it was ultimately overshadowed by the technically less powerful, Atari 2600.",
        "url": "https://www.giantbomb.com/intellivision/3045-51/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/24/176540-intellivision_small.jpg",
    },
    UPS.INTELLIVISION_AMICO: {
        "id": 181,
        "slug": "intellivision-amico",
        "title": "Intellivision Amico",
        "description": "A console that's intended to be a reimagining of the Intellivision brand.",
        "url": "https://www.giantbomb.com/intellivision-amico/3045-181/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/3161447-dims.jpeg",
    },
    UPS.IOS: {
        "id": 96,
        "slug": "iphone",
        "title": "iPhone",
        "description": "The iPhone is a multimedia multi-touch smartphone created by Apple Inc.",
        "url": "https://www.giantbomb.com/iphone/3045-96/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3383085-5925865434-Apple.jpg",
    },
    UPS.IPAD: {
        "id": 121,
        "slug": "ipad",
        "title": "iPad",
        "description": "The iPad is a series of touch-screen tablet devices developed by Apple. The iPad can browse the web, playback local and streamed content, and run a large variety of third party apps, including games.",
        "url": "https://www.giantbomb.com/ipad/3045-121/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3383081-8892238218-ipad-pro-12-select-wifi-spacegray-202104_FMT_WHH.jpg",
    },
    UPS.IPOD_CLASSIC: {
        "id": 72,
        "slug": "ipod",
        "title": "iPod Classic",
        "description": "The iPod is a line of portable media players and portable digital audio players developed and marketed by Apple Inc.",
        "url": "https://www.giantbomb.com/ipod/3045-72/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/2564462-ipod.png",
    },
    UPS.JAGUAR: {
        "id": 28,
        "slug": "jaguar",
        "title": "Jaguar",
        "description": "The Atari Jaguar was the first 64-Bit game console, and Atari's final console.",
        "url": "https://www.giantbomb.com/jaguar/3045-28/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954600-atari-jaguar-console-set.jpg",
    },
    UPS.LASERACTIVE: {
        "id": 92,
        "slug": "pioneer-laseractive",
        "title": "Pioneer LaserActive",
        "description": "Pioneer LaserActive was a failed modular laserdisc-based game console notable for its use of expansion modules as well as being the second highest priced console of all time.",
        "url": "https://www.giantbomb.com/pioneer-laseractive/3045-92/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4/176058-laserinteractive.jpg",
    },
    UPS.LEAPFROG_EXPLORER: {
        "id": 185,
        "slug": "leapster-explorer",
        "title": "Leapster Explorer",
        "description": "Leapster Explorer is a cartridge-based handheld console developed by LeapFrog and intended for children under the age of ten.",
        "url": "https://www.giantbomb.com/leapster-explorer/3045-185/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3195577-91b99%2B96oel._ac_sx425_.jpg",
    },
    UPS.LEAPSTER: {
        "id": 89,
        "slug": "leapster",
        "title": "Leapster",
        "description": "The LeapFrog Leapster is a stylus-based educational game device aimed at children under 10.",
        "url": "https://www.giantbomb.com/leapster/3045-89/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10607-leapster.jpg",
    },
    UPS.LEAPSTER_EXPLORER_SLASH_LEADPAD_EXPLORER: {
        "id": 186,
        "slug": "leappad",
        "title": "LeapPad",
        "description": "LeapPad is a series of tablets developed by LeapFrog beginning in 1999. They are primarily intended for children.",
        "url": "https://www.giantbomb.com/leappad/3045-186/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3195586-91siqfml3ul._ac_sl1500_.jpg",
    },
    UPS.LINUX: {
        "id": 152,
        "slug": "linux",
        "title": "Linux",
        "description": "The Linux operating system was initially released in 1991 and has gone on to become a very popular free alternative to other, commercial systems.",
        "url": "https://www.giantbomb.com/linux/3045-152/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/1/14761/2435328-tux.png",
    },
    UPS.LUNA: {
        "id": 199,
        "slug": "amazon-luna",
        "title": "Amazon Luna",
        "description": 'Amazon\'s cloud-based streaming service takes a "channel" style approach to access, with a basic monthly fee for the Luna core and additional monthly fees for more games from specific publishers.',
        "url": "https://www.giantbomb.com/amazon-luna/3045-199/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/3244842-luna.jpg",
    },
    UPS.LYNX: {
        "id": 7,
        "slug": "atari-lynx",
        "title": "Atari Lynx",
        "description": "Atari's 1989 color, backlit handheld console",
        "url": "https://www.giantbomb.com/atari-lynx/3045-7/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10608-lynx2.jpg",
    },
    UPS.MAC: {
        "id": 17,
        "slug": "mac",
        "title": "Mac",
        "description": 'The Macintosh (Mac) line of personal computers is designed and developed by Apple, Inc. - formerly Apple Computer, Inc. It runs macOS, a Unix operating system. Its current version, macOS 13.4 "Ventura" was released on May 18, 2023.',
        "url": "https://www.giantbomb.com/mac/3045-17/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/5150/1500874-overview_gallery3_20090828.jpg",
    },
    UPS.MAGIC_LEAP_ONE: {
        "id": 173,
        "slug": "magic-leap-one",
        "title": "Magic Leap One",
        "description": 'The Magic Leap One launched as a developer-focused "Creator Edition" in August 2018.',
        "url": "https://www.giantbomb.com/magic-leap-one/3045-173/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/3059027-product-family-shot_3x.jpeg",
    },
    UPS.MEGA_DUCK_SLASH_COUGAR_BOY: {
        "id": 137,
        "slug": "mega-duck",
        "title": "Mega Duck",
        "description": "The Mega Duck is a 1993 handheld that was released in some territories under the name Cougar Boy. It was released as the Mega Duck in France, Germany, Brazil, and China. The handheld was also released as the Cougar Boy in the USA and some other countries.",
        "url": "https://www.giantbomb.com/mega-duck/3045-137/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/12/126726/1755677-8347458953222508.jpg",
    },
    UPS.MEMOTECH_MTX: {
        "id": 206,
        "slug": "memotech-mtx",
        "title": "Memotech MTX",
        "description": "The Memotech MTX is a series of British-developed home computers released in 1983 and 1984.",
        "url": "https://www.giantbomb.com/memotech-mtx/3045-206/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3341703-images.jpeg",
    },
    UPS.META_QUEST_2: {
        "id": 177,
        "slug": "meta-quest",
        "title": "Meta Quest",
        "description": "Oculus Quest is a self-contained virtual reality platform from the makers of the Oculus Rift.",
        "url": "https://www.giantbomb.com/meta-quest/3045-177/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/3099536-71nk%2Bjjlzzl._sx679_.jpg",
    },
    UPS.MICROBEE: {
        "id": 168,
        "slug": "micro-bee",
        "title": "MicroBee",
        "description": "The MicroBee line of computers started with the release of a mail-order kit computer in 1982.",
        "url": "https://www.giantbomb.com/micro-bee/3045-168/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/2974952-microbee_computer-in-a-book.jpg",
    },
    UPS.MICROVISION: {
        "id": 90,
        "slug": "microvision",
        "title": "Microvision",
        "description": "The first gaming handheld, Surpizingly big but extremely rare.",
        "url": "https://www.giantbomb.com/microvision/3045-90/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10813-MicroVision.jpg",
    },
    UPS.MONON_COLOR: {
        "id": 204,
        "slug": "monon-color",
        "title": "Monon Color",
        "description": "The Monon Color is a portable game console produced by Nintendo. It was released in Japan in 1980.",
        "url": "https://www.giantbomb.com/monon-color/3045-204/",
        "url_logo": "https://www.giantbomb.com/a/uploads/scale_small/0/1992/3341671-4c3443fd23473ce64296b645f6507ade.jpeg",
    },
    UPS.MSX: {
        "id": 15,
        "slug": "msx",
        "title": "MSX",
        "description": "MSX is a standardized home computer architecture. It was popular in Japan, South Korea, Brazil, Netherlands, France, Spain, Finland, Arabian Gulf countries and former Soviet Union during the 1980s. Like the PC of today, the MSX computers were manufactured by many different companies.",
        "url": "https://www.giantbomb.com/msx/3045-15/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/25/176106-msx_philips_vg8020.jpg",
    },
    UPS.MULTI_8: {
        "id": 205,
        "slug": "mitsubishi-multi-8",
        "title": "Mitsubishi Multi 8",
        "description": "The Mitsubishi Multi 8 is a home computer released in Japan in 1983. Several cartridge-based games were released for it.",
        "url": "https://www.giantbomb.com/mitsubishi-multi-8/3045-205/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3341686-multi8.jpeg",
    },
    UPS.N64: {
        "id": 43,
        "slug": "nintendo-64",
        "title": "Nintendo 64",
        "description": "The successor to the SNES was Nintendo's first system designed specifically to handle polygonal 3D graphics.",
        "url": "https://www.giantbomb.com/nintendo-64/3045-43/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/1426281-logo.jpg",
    },
    UPS.NDS: {
        "id": 52,
        "slug": "nintendo-ds",
        "title": "Nintendo DS",
        "description": "The Nintendo DS is a handheld featuring two screens, one of which is a resistive touchscreen. Four different models are available: the original DS, the DS Lite, the DSi, the DSi XL.",
        "url": "https://www.giantbomb.com/nintendo-ds/3045-52/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/2122822-ds.png",
    },
    UPS.NEO_GEO_CD: {
        "id": 167,
        "slug": "neo-geo-cd",
        "title": "Neo Geo CD",
        "description": "The Neo Geo CD was released after its cartridge-based equivalent, in an effort to reduce manufacturing costs.",
        "url": "https://www.giantbomb.com/neo-geo-cd/3045-167/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/25/176112-neogeocd.jpg",
    },
    UPS.NEO_GEO_POCKET: {
        "id": 80,
        "slug": "neo-geo-pocket",
        "title": "Neo Geo Pocket",
        "description": "The Neo Geo Pocket is SNK Playmore's first handheld video game console. The console did not do as well as expected, and had a short life span and small game library.",
        "url": "https://www.giantbomb.com/neo-geo-pocket/3045-80/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954592-neo-geo-pocket-anthra-left.jpg",
    },
    UPS.NEO_GEO_POCKET_COLOR: {
        "id": 81,
        "slug": "neo-geo-pocket-color",
        "title": "Neo Geo Pocket Color",
        "description": "The Neo Geo Pocket Color is a 16 bit color handheld console from SNK.",
        "url": "https://www.giantbomb.com/neo-geo-pocket-color/3045-81/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/1426322-logo.jpg",
    },
    UPS.NEOGEOAES: {
        "id": 25,
        "slug": "neo-geo",
        "title": "Neo Geo",
        "description": "The Neo Geo was a console released by SNK in 1990, featuring a 16/32-bit 68000 CPU with an additional 8-bit Z80 CPU and custom 24-bit GPU chipset. An arcade-based console considerably powerful for a home system at the time, the Neo Geo was notoriously expensive (costing $650 at launch) and aggressively marketed as an Advanced Entertainment System (AES).",
        "url": "https://www.giantbomb.com/neo-geo/3045-25/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/1/13362/613868-neo_20geo.jpg",
    },
    UPS.NES: {
        "id": 21,
        "slug": "nintendo-entertainment-system",
        "title": "Nintendo Entertainment System",
        "description": "The NES, also known as Famicom, launched in 1983 in Japan and 1985 in North America, where the video game industry was headed downhill due to a deluge of poor games and over-saturation. Nintendo's second home console became an enormous success, establishing consoles as a mainstream market in Japan and pulling the North American industry back to its feet.",
        "url": "https://www.giantbomb.com/nintendo-entertainment-system/3045-21/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/9/99864/2419866-nes_console_set.png",
    },
    UPS.NEW_NINTENDON3DS: {
        "id": 156,
        "slug": "new-nintendo-3ds",
        "title": "New Nintendo 3DS",
        "description": "Nintendo's \"New 3DS\" adds some additional control functionality and horsepower, allowing for some games that can only run on the new hardware, not on Nintendo's original 3DS.",
        "url": "https://www.giantbomb.com/new-nintendo-3ds/3045-156/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/8/82063/2676248-photo_3ds_01_wmcs1e.jpg",
    },
    UPS.NGAGE: {
        "id": 34,
        "slug": "n-gage",
        "title": "N-Gage",
        "description": "The N-Gage (later re-released as N-Gage QD) was a failed gaming platform developed by phone manufacturer Nokia. Games in MMC-Card format were sold for the platform, and towards the end, games were available for download to your own MMC. ",
        "url": "https://www.giantbomb.com/n-gage/3045-34/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/1/14912/702653-ngageqd.jpg",
    },
    UPS.NGC: {
        "id": 23,
        "slug": "gamecube",
        "title": "GameCube",
        "description": "The Nintendo GameCube is a video game console released by Nintendo on September 15, 2001 in Japan, November 18, 2001 in North America, May 3, 2002 in Europe, and May 17, 2002 in Australia.",
        "url": "https://www.giantbomb.com/gamecube/3045-23/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/1426256-logo.jpg",
    },
    UPS.NUON: {
        "id": 85,
        "slug": "nuon",
        "title": "NUON",
        "description": 'Originally called "Project X", the Nuon started out as a concept for a stand alone console but instead became a built in 3D enhancement technology in a handful of DVD players.  NUON technology fared abysmally and the platform only managed to get 8 titles.',
        "url": "https://www.giantbomb.com/nuon/3045-85/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954590-nuon-n2000-wcontroller-l.jpg",
    },
    UPS.ODYSSEY: {
        "id": 74,
        "slug": "odyssey",
        "title": "Odyssey",
        "description": "The Magnavox Odyssey was the first home video game console.",
        "url": "https://www.giantbomb.com/odyssey/3045-74/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/13/139866/2606039-3801669138-Magna.jpg",
    },
    UPS.ODYSSEY_2: {
        "id": 60,
        "slug": "odyssey-2",
        "title": "Odyssey 2",
        "description": "The Odyssey 2 was Magnavox's second console, which competed with the Atari 2600 and Fairchild Channel F.",
        "url": "https://www.giantbomb.com/odyssey-2/3045-60/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/25/176130-o2_hard.jpg",
    },
    UPS.ORIC: {
        "id": 195,
        "slug": "oric",
        "title": "Oric",
        "description": "Oric was a series of computers produced by Tangerine Computer Systems between 1981 and 1986.",
        "url": "https://www.giantbomb.com/oric/3045-195/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3220230-oric1.jpg",
    },
    UPS.OUYA: {
        "id": 154,
        "slug": "ouya",
        "title": "Ouya",
        "description": "The Ouya is an Android-based device that hooks up to TVs and plays video games.",
        "url": "https://www.giantbomb.com/ouya/3045-154/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/2462186-ouya.jpg",
    },
    UPS.PC_6001: {
        "id": 115,
        "slug": "nec-pc-6001",
        "title": "NEC PC-6001",
        "description": "The first in NEC's PC-6000 line of computers.",
        "url": "https://www.giantbomb.com/nec-pc-6001/3045-115/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4/1151382-250px_nec_pc_6001.jpg",
    },
    UPS.PC_8800_SERIES: {
        "id": 47,
        "slug": "nec-pc-8800-series",
        "title": "NEC PC-8800 Series",
        "description": "The NEC PC-8800 Series is a series of home computers released by NEC in 1981.",
        "url": "https://www.giantbomb.com/nec-pc-8800-series/3045-47/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3195565-entex-selectagame.jpg",
    },
    UPS.PC_9800_SERIES: {
        "id": 112,
        "slug": "nec-pc-9801",
        "title": "NEC PC-9801",
        "description": "A 16/32-bit Japanese personal computer system launched by NEC in 1982. It was the most successful computer platform in Japan and one of the best-selling computer systems of the 20th century. It has a very large video game library with thousands of titles, the majority of which were never released outside Japan.",
        "url": "https://www.giantbomb.com/nec-pc-9801/3045-112/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/5/59247/1129864-pc_9801_l.jpg",
    },
    UPS.PC_FX: {
        "id": 75,
        "slug": "pc-fx",
        "title": "PC-FX",
        "description": "The NEC PC-FX was a console designed in the form of a PC and planned to be upgradable.  It failed due to lack of 3D graphical power and little developer support.  The PC-FX is known for its large percentage of adult titles and was NEC Corporation's last gaming console.",
        "url": "https://www.giantbomb.com/pc-fx/3045-75/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954599-nec-pc-fx-wcontroller-r.jpg",
    },
    UPS.PHILIPS_CD_I: {
        "id": 27,
        "slug": "cd-i",
        "title": "CD-i",
        "description": "The CD-i was the first CD-based game console. Produced by Philips, it was intended to be a computer for your living room.",
        "url": "https://www.giantbomb.com/cd-i/3045-27/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10173-cd-i.jpg",
    },
    UPS.PINBALL: {
        "id": 83,
        "slug": "pinball",
        "title": "Pinball",
        "description": 'In a pinball machine the player is in control of two or more "flippers" (small movable bars) that are used to shoot a metal ball against different physical targets inside the machine.',
        "url": "https://www.giantbomb.com/pinball/3045-83/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/3948/955933-6a00d83452989a69e2010536fbd197970b_800wi.jpg",
    },
    UPS.PIPPIN: {
        "id": 102,
        "slug": "pippin",
        "title": "Pippin",
        "description": "This short-lived multimedia device was designed by Apple and manufactured by Bandai.  It is widely regarded as one of the worst video game consoles of all time.",
        "url": "https://www.giantbomb.com/pippin/3045-102/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954591-pippin-atmark-console-set.jpg",
    },
    UPS.PLATO: {
        "id": 111,
        "slug": "plato",
        "title": "PLATO",
        "description": "PLATO stands for Programmed Logic for Automated Teaching Operations. Mainly used for assisting in instruction and offering coursework originally built by the University of Illinois. ",
        "url": "https://www.giantbomb.com/plato/3045-111/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/1101577-240px_platovterm1981.jpg",
    },
    UPS.PLAYDATE: {
        "id": 178,
        "slug": "playdate",
        "title": "Playdate",
        "description": "Playdate is a handheld designed by Panic. It has unique controls, a 'season' of games and is an open development platform.",
        "url": "https://www.giantbomb.com/playdate/3045-178/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3102813-screen%20shot%202019-05-23%20at%209.05.10%20pm.png",
    },
    UPS.PLAYDIA: {
        "id": 127,
        "slug": "bandai-playdia",
        "title": "Bandai Playdia",
        "description": "The Bandai Playdia was an early nineties video game console released only in Japan.",
        "url": "https://www.giantbomb.com/bandai-playdia/3045-127/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/3/30183/1661326-playdia.jpg",
    },
    UPS.POKEMON_MINI: {
        "id": 134,
        "slug": "pokemon-mini",
        "title": "Pokémon mini",
        "description": "The Pokemon Mini is a handheld game system developed by Nintendo in the early 2000's focusing solely on mini-games within the Pokémon universe.",
        "url": "https://www.giantbomb.com/pokemon-mini/3045-134/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/1749907-pokemonmini.jpg",
    },
    UPS.PS2: {
        "id": 19,
        "slug": "playstation-2",
        "title": "PlayStation 2",
        "description": "Sony's PlayStation 2 is the second home video game console produced by Sony Computer Entertainment Incorporated, and to date is the best-selling home console of all time, with an install base of 150 million units since its launch.",
        "url": "https://www.giantbomb.com/playstation-2/3045-19/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/9595/438868-ps2_full_large.jpg",
    },
    UPS.PS3: {
        "id": 35,
        "slug": "playstation-3",
        "title": "PlayStation 3",
        "description": "The PlayStation 3 (often abbreviated PS3) is the third home video game console created and released by Sony Computer Entertainment Inc.",
        "url": "https://www.giantbomb.com/playstation-3/3045-35/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/1426360-logo.jpg",
    },
    UPS.PS4: {
        "id": 146,
        "slug": "playstation-4",
        "title": "PlayStation 4",
        "description": "PlayStation 4 is Sony's fourth home video game console, released on November 15, 2013 in North America, and November 29, 2013 in Europe. On November 10 2016, Sony released the Playstation 4 Pro, an updated version of the console targeting 4K gaming.",
        "url": "https://www.giantbomb.com/playstation-4/3045-146/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/5/56742/2495936-9012444134_80ba47fd6e_o.jpg",
    },
    UPS.PS5: {
        "id": 176,
        "slug": "playstation-5",
        "title": "PlayStation 5",
        "description": "Sony's fifth PlayStation console launched on November 12, 2020 with two models: a standard edition with a disk drive and a digital edition without.",
        "url": "https://www.giantbomb.com/playstation-5/3045-176/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3202024-eaqr77pu4aavlo6.jpeg",
    },
    UPS.PSP: {
        "id": 18,
        "slug": "playstation-portable",
        "title": "PlayStation Portable",
        "description": "PlayStation Portable (PSP) is Sony's first entry into the handheld gaming market. The PSP also sports multimedia features including music and video playback, a photo viewer, and an online store. Several model revisions have been released: the PSP-2000, 3000, PSPgo and the PSP-E1000.",
        "url": "https://www.giantbomb.com/playstation-portable/3045-18/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/2122792-pspmain.png",
    },
    UPS.PSVITA: {
        "id": 129,
        "slug": "playstation-vita",
        "title": "PlayStation Vita",
        "description": "PlayStation Vita is Sony's second handheld gaming device.",
        "url": "https://www.giantbomb.com/playstation-vita/3045-129/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/2122519-vita.png",
    },
    UPS.PSX: {
        "id": 22,
        "slug": "playstation",
        "title": "PlayStation",
        "description": "Sony's first video game console established the PlayStation brand. It dominated the 32/64-bit era and was the best-selling home console up until the PlayStation 2.",
        "url": "https://www.giantbomb.com/playstation/3045-22/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/1426393-logo.jpg",
    },
    UPS.R_ZONE: {
        "id": 103,
        "slug": "r-zone",
        "title": "R-Zone",
        "description": "The R-Zone was a heavily marketed, cartridge based LCD handheld that ultimately flopped.  It marked Tiger's first attempt at a handheld game system.",
        "url": "https://www.giantbomb.com/r-zone/3045-103/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954595-tiger-rzone-headset.jpg",
    },
    UPS.RCA_STUDIO_II: {
        "id": 131,
        "slug": "rca-studio-ii",
        "title": "RCA Studio II",
        "description": "Considered by many to be one of the worst video game consoles ever released, the RCA Studio II featured monochrome graphics, number pad controllers, and single channel sound.",
        "url": "https://www.giantbomb.com/rca-studio-ii/3045-131/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/12/126726/1745663-giant_bomb_sub_3.jpg",
    },
    UPS.RX_78: {
        "id": 201,
        "slug": "bandai-rx-78",
        "title": "Bandai RX-78",
        "description": "The Bandai RX-78 is a home computer that was released in July 1983 in Japan for ¥59,800.",
        "url": "https://www.giantbomb.com/bandai-rx-78/3045-201/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3300216-screenshot2021-06-29at8.51.54pm.png",
    },
    UPS.SAM_COUPE: {
        "id": 162,
        "slug": "sam-coupe",
        "title": "SAM Coupé",
        "description": "The SAM Coupé could partially emulate the ZX Spectrum, but also ran some games of its own.",
        "url": "https://www.giantbomb.com/sam-coupe/3045-162/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/2810186-1964411787-SAM_C.jpg",
    },
    UPS.SATELLAVIEW: {
        "id": 98,
        "slug": "satellaview",
        "title": "Satellaview",
        "description": "The Satellaview was an add-on for the Super Famicom, released only in Japan.  It downloaded games and news via satellite broadcast, and received live, streaming voice acting and hints for some games.",
        "url": "https://www.giantbomb.com/satellaview/3045-98/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/429/177828-600px_satellaview_with_super_famicom.jpg",
    },
    UPS.SATURN: {
        "id": 42,
        "slug": "saturn",
        "title": "Saturn",
        "description": "A 32-bit game console developed by Sega. Due to development difficulties and the rising popularity of the PlayStation and N64, the Saturn was discontinued overseas in 1998, but continued to sell in Japan until 2000. It was Sega's most successful console in Japan yet their least successful console overseas.",
        "url": "https://www.giantbomb.com/saturn/3045-42/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/6/60997/1142464-sega_saturn.jpg",
    },
    UPS.SEGA_PICO: {
        "id": 105,
        "slug": "sega-pico",
        "title": "Sega Pico",
        "description": "Sega Pico is an educational video game system aimed at children. The system was also the first Sega system to carry Nintendo licensed games.",
        "url": "https://www.giantbomb.com/sega-pico/3045-105/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/7465/1761423-pico.jpg",
    },
    UPS.SEGA32X: {
        "id": 31,
        "slug": "sega-32x",
        "title": "Sega 32X",
        "description": "Sega's short-lived jump into the 32-bit gaming era began with this add-on to the Sega Genesis.",
        "url": "https://www.giantbomb.com/sega-32x/3045-31/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954598-800px-sega-genesis-model2-32x.jpg",
    },
    UPS.SEGACD: {
        "id": 29,
        "slug": "sega-cd",
        "title": "Sega CD",
        "description": "The Sega CD was one of the first CD-ROM based gaming consoles. The extra storage space this medium allowed gave rise to inclusion of full motion video, higher quality audio, and improved graphics in games.  ",
        "url": "https://www.giantbomb.com/sega-cd/3045-29/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/25/176099-20070529172508_sega_mega_cd_ii__pal_.jpg",
    },
    UPS.SELECT_A_GAME: {
        "id": 184,
        "slug": "entex-select-a-game",
        "title": "Entex Select-A-Game",
        "description": "Entex's Select-A-Game is a handheld console that was released in 1981. Only six games were officially released before it was discontinued.",
        "url": "https://www.giantbomb.com/entex-select-a-game/3045-184/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3195565-entex-selectagame.jpg",
    },
    UPS.SERIES_X_S: {
        "id": 179,
        "slug": "xbox-series-xs",
        "title": "Xbox Series X|S",
        "description": "The fourth Xbox console from Microsoft launched on November 10, 2020 with two distinct models; Series X and Series S.",
        "url": "https://www.giantbomb.com/xbox-series-xs/3045-179/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3241522-untitled-2.png",
    },
    UPS.SG1000: {
        "id": 141,
        "slug": "sega-sg-1000",
        "title": "Sega SG-1000",
        "description": "Sega's first foray into home game consoles. Released in 1983 alongside its rival, the Famicom, the SG-1000 is a home console and did not receive a worldwide release. It was later succeeded by the Sega Mark III, better known as the Sega Master System.",
        "url": "https://www.giantbomb.com/sega-sg-1000/3045-141/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/12/126726/1770079-giant_bomb_sub.jpg",
    },
    UPS.SHARP_MZ_80B20002500: {
        "id": 128,
        "slug": "sharp-mz",
        "title": "Sharp MZ",
        "description": "The Sharp MZ is a home computer that was first released in the late 1970s. It was one of the first home computers to play video games.",
        "url": "https://www.giantbomb.com/sharp-mz/3045-128/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/5/59247/1674132-mz700.png",
    },
    UPS.SHARP_X68000: {
        "id": 95,
        "slug": "sharp-x68000",
        "title": "Sharp X68000",
        "description": "The Sharp X68000 is a 16/32-bit Japanese computer platform that was originally released in 1987. It was the first home system to offer arcade-quality graphics, serving as the development machine for the Capcom CPS arcade system over the next several years. It was the most powerful home gaming system of the 1980s.",
        "url": "https://www.giantbomb.com/sharp-x68000/3045-95/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4/176060-x68000xvihd8.jpg",
    },
    UPS.SMAKY: {
        "id": 183,
        "slug": "smaky",
        "title": "Smaky",
        "description": "The Smaky (SMArt KeYboard) is a series of computers developed in Switzerland beginning in 1974.",
        "url": "https://www.giantbomb.com/smaky/3045-183/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3185777-2560px-smaky_100_img_4149.jpg",
    },
    UPS.SMC_777: {
        "id": 160,
        "slug": "sony-smc777",
        "title": "Sony SMC-777",
        "description": "Many of Sony's SMC series of machines came with built-in genlocks for video production use, but games were also released on some of the different variants. It is also the first computer to utilize 3.5\" diskettes.",
        "url": "https://www.giantbomb.com/sony-smc777/3045-160/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/2791151-smc777-2.jpg",
    },
    UPS.SMS: {
        "id": 8,
        "slug": "sega-master-system",
        "title": "Sega Master System",
        "description": "The 8-bit Master System, while not embraced by a large audience in the US and Japan, was a major success in Europe and South America, and it remains an important and entertaining console that laid the foundation for generations of future console releases from Sega.",
        "url": "https://www.giantbomb.com/sega-master-system/3045-8/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/25/176128-sega_master_system__6_.jpg",
    },
    UPS.SNES: {
        "id": 9,
        "slug": "super-nintendo-entertainment-system",
        "title": "Super Nintendo Entertainment System",
        "description": "The Super Nintendo Entertainment System was the second home console released by Nintendo.",
        "url": "https://www.giantbomb.com/super-nintendo-entertainment-system/3045-9/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/8/82063/2287891-snes_sfc.jpg",
    },
    UPS.SOCRATES: {
        "id": 169,
        "slug": "vtech-socrates",
        "title": "VTech Socrates",
        "description": "The VTech Socrates was originally released in 1988.",
        "url": "https://www.giantbomb.com/vtech-socrates/3045-169/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/2975817-4025802893-",
    },
    UPS.SORD_M5: {
        "id": 193,
        "slug": "sord-m5",
        "title": "Sord M5",
        "description": "The Sord M5 is a home computer produced by the Sord Corporation in 1982.",
        "url": "https://www.giantbomb.com/sord-m5/3045-193/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3195653-screen%20shot%202020-05-25%20at%201.10.10%20pm.png",
    },
    UPS.STADIA: {
        "id": 175,
        "slug": "google-stadia",
        "title": "Google Stadia",
        "description": "Stadia was a streaming platform for games powered by Google's cloud infrastructure.",
        "url": "https://www.giantbomb.com/google-stadia/3045-175/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/3184321-images.jpg",
    },
    UPS.STREAMING: {
        "id": 194,
        "slug": "stream",
        "title": "Stream",
        "description": "Stream games are those designed to be played by viewers on streaming platforms (i.e. Twitch). The streamer initiates the game, viewers join, and watch the events play out.",
        "url": "https://www.giantbomb.com/stream/3045-194/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3216290-gpbstreamrace.png",
    },
    UPS.SUPER_ACAN: {
        "id": 151,
        "slug": "super-acan",
        "title": "Super A'Can",
        "description": "Funtech released the Super A'Can in Taiwan in 1995. Only 12 games were produced for the 16-bit console before it was scrapped.",
        "url": "https://www.giantbomb.com/super-acan/3045-151/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954583-super-acan-console-set-h.jpg",
    },
    UPS.SUPERGRAFX: {
        "id": 119,
        "slug": "supergrafx",
        "title": "SuperGrafx",
        "description": "This upgraded PC-Engine was released in Japan in 1989. Few exclusive titles for the system were ever released.",
        "url": "https://www.giantbomb.com/supergrafx/3045-119/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/3/30116/1317921-pcengine_supergrafx.jpg",
    },
    UPS.SUPERVISION: {
        "id": 147,
        "slug": "watara-supervision",
        "title": "Watara Supervision",
        "description": "The Watara Supervision (known as the QuickShot Supervision in the UK) is a handheld with a Game Boy-like form factor. It was originally released in 1992.",
        "url": "https://www.giantbomb.com/watara-supervision/3045-147/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954576-watara-supervision-tilted.jpg",
    },
    UPS.SWITCH: {
        "id": 157,
        "slug": "nintendo-switch",
        "title": "Nintendo Switch",
        "description": "Nintendo's home console that can be turned into a portable device by removing it from its TV-dock. Launched worldwide on March 3, 2017.",
        "url": "https://www.giantbomb.com/nintendo-switch/3045-157/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/2894693-screen%20shot%202016-10-20%20at%2010.04.36%20am.png",
    },
    UPS.SWITCH_2: {
        "id": 210,
        "slug": "nintendo-switch-2",
        "title": "Nintendo Switch 2",
        "description": "The Nintendo Switch 2 is Nintendo's eighth home console and the successor to the Nintendo Switch.",
        "url": "https://www.giantbomb.com/nintendo-switch-2/3045-210/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3679772-untitled-1.png",
    },
    UPS.TANDY_VIS: {
        "id": 153,
        "slug": "memorex-md-2500-vis",
        "title": "Memorex MD 2500 VIS",
        "description": "The Memorex MD 2500, also known as the Tandy VIS, was released in 1992. It ran a version of Windows that can be described as a precursor to WinCE and primarily focused on educational games.",
        "url": "https://www.giantbomb.com/memorex-md-2500-vis/3045-153/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954664-5814140637-C2fBm.jpg",
    },
    UPS.TG16: {
        "id": 55,
        "slug": "turbografx-16",
        "title": "TurboGrafx-16",
        "description": "The TurboGrafx-16, or PC Engine, is a console that was marketed as the first 16-bit console. It was for some time the market leader in Japan, but failed to capture a large market share in North America. It was best known for featuring the first CD-ROM peripheral, the TurboGrafx-CD. It also introduced features such as a multitap peripheral, internal save memory, and RAM expansions.",
        "url": "https://www.giantbomb.com/turbografx-16/3045-55/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/25/176127-turbografx_16.jpg",
    },
    UPS.TI_994A: {
        "id": 48,
        "slug": "ti-994a",
        "title": "TI-99/4A",
        "description": "A home computer created by Texas Instruments and released in 1981. It was the first home console to feature a 16-bit processor and included a prototype plug-and-play serial bus similar to what would become known as USB.",
        "url": "https://www.giantbomb.com/ti-994a/3045-48/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/1427020-logo.jpg",
    },
    UPS.TOMAHAWK_F1: {
        "id": 164,
        "slug": "fuze-tomahawk-f1",
        "title": "Fuze Tomahawk F1",
        "description": "The Android-based Tomahawk F1 is built on Android and is aimed directly at the Chinese market.",
        "url": "https://www.giantbomb.com/fuze-tomahawk-f1/3045-164/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/2850182-screen%20shot%202016-05-10%20at%2010.48.20%20am.png",
    },
    UPS.TOMY_TUTOR: {
        "id": 165,
        "slug": "tomy-tutor",
        "title": "Tomy Tutor",
        "description": "Tomy released the Tutor computer in 1982. It was primarily known in Japan, where it was launched as the Tomy Pyuuta.",
        "url": "https://www.giantbomb.com/tomy-tutor/3045-165/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/2905352-tomy_tutor_white_background.jpg",
    },
    UPS.TRS_80: {
        "id": 63,
        "slug": "trs-80",
        "title": "TRS-80",
        "description": "The TRS-80 was a very popular early microcomputer with standout features such as a full keyboard, included monitor, impressive floating point BASIC programming language, and a $600 pricepoint.",
        "url": "https://www.giantbomb.com/trs-80/3045-63/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/25/176129-trs80_2.jpg",
    },
    UPS.TRS_80_COLOR_COMPUTER: {
        "id": 68,
        "slug": "trs-80-coco",
        "title": "TRS-80 Color Computer",
        "description": "The TRS-80 Color Computer is a home computer released by Tandy in 1981.",
        "url": "https://www.giantbomb.com/trs-80-coco/3045-62/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3195565-entex-selectagame.jpg",
    },
    UPS.TURBOGRAFX_CD: {
        "id": 53,
        "slug": "turbografx-cd",
        "title": "TurboGrafx-CD",
        "description": "NEC's CD-ROM add-on for its PC Engine / TurboGrafx-16 console. Originally released as the PC Engine CD-ROM² in Japan in 1988, this was the first system to use the CD-ROM format. It would later be released in North America as the TurboGrafx-CD in 1989. While it had little impact on the ailing TurboGrafx-16 in North America, this add-on boosted PC Engine sales in Japan.",
        "url": "https://www.giantbomb.com/turbografx-cd/3045-53/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/25/176113-turbografx.jpg",
    },
    UPS.TVBOY: {
        "id": 196,
        "slug": "gakken-compact-vision-tv-boy",
        "title": "Gakken Compact Vision TV Boy",
        "description": "The Compact Vision TV Boy is a game console developed by Gakken in 1983. Only six games were released.",
        "url": "https://www.giantbomb.com/gakken-compact-vision-tv-boy/3045-196/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3220237-screenshot2020-07-15at5.50.02pm.png",
    },
    UPS.TVOS: {
        "id": 159,
        "slug": "apple-tv",
        "title": "Apple tvOS",
        "description": "The fourth-generation Apple TV adds an App Store, opening up the availability of third-party apps and games to a wider degree. The remote also has motion capabilities, opening it up as a game device.",
        "url": "https://www.giantbomb.com/apple-tv/3045-159/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/3276566-0122928757-0-599.jpg",
    },
    UPS.VC_4000: {
        "id": 191,
        "slug": "interton-vc-4000",
        "title": "Interton VC 4000",
        "description": 'The Interton Video Computer 4000 is an 8-bit console released in Europe (primarily Germany) in 1978. Around forty "cassettes" were released for the system.',
        "url": "https://www.giantbomb.com/interton-vc-4000/3045-191/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3195628-screen%20shot%202020-05-25%20at%2012.41.55%20pm.png",
    },
    UPS.VECTREX: {
        "id": 76,
        "slug": "vectrex",
        "title": "Vectrex",
        "description": "The Vectrex was a short lived home video game system that used Vector graphics. It is often considered as one of the first home video gaming systems.",
        "url": "https://www.giantbomb.com/vectrex/3045-76/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954660-2340135697-DAYmR.jpg",
    },
    UPS.VIC_20: {
        "id": 30,
        "slug": "vic-20",
        "title": "VIC-20",
        "description": "An 8-bit computer produced by Commodore Electronics Ltd. Also known as the VIC-1001, it was the first microcomputer to sell one million units.",
        "url": "https://www.giantbomb.com/vic-20/3045-30/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4/176108-vic.jpg",
    },
    UPS.VIEW_MASTER: {
        "id": 163,
        "slug": "viewmaster-interactive-vision",
        "title": "View-Master Interactive Vision",
        "description": "The View-Master Interactive Vision is a VHS-based platform designed to play a small handful of Sesame Street and other edutainment-based games.",
        "url": "https://www.giantbomb.com/viewmaster-interactive-vision/3045-163/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/2812035-8637007543-ViewM.jpg",
    },
    UPS.VIRTUALBOY: {
        "id": 79,
        "slug": "virtual-boy",
        "title": "Virtual Boy",
        "description": "The Virtual Boy pioneered portable 3D gaming, but became one of Nintendo's biggest market and financial blunders. Despite innovative display technology, various design and marketing mistakes doomed it to poor sales and quick retirement. Fewer than two dozen titles came out worldwide and only 14 in North America.",
        "url": "https://www.giantbomb.com/virtual-boy/3045-79/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954596-800px-virtual-boy-set.png",
    },
    UPS.VSMILE: {
        "id": 82,
        "slug": "vsmile",
        "title": "V.Smile",
        "description": "The V.Smile is an educational video game console made for young children.",
        "url": "https://www.giantbomb.com/vsmile/3045-82/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10324-vsmile.jpg",
    },
    UPS.WII: {
        "id": 36,
        "slug": "wii",
        "title": "Wii",
        "description": "The Nintendo Wii is a home video game console released on November 19, 2006. The Wii's main selling point was the innovative use of motion controls that its signature Wii Remote and Nunchuk controllers allowed for. It became the best selling home console of its respective generation of hardware.",
        "url": "https://www.giantbomb.com/wii/3045-36/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/10616-wii.jpg",
    },
    UPS.WIIU: {
        "id": 139,
        "slug": "wii-u",
        "title": "Wii U",
        "description": "The Nintendo Wii U, the follow-up to the monstrously popular Nintendo Wii console, launched in North America on November 18th 2012.",
        "url": "https://www.giantbomb.com/wii-u/3045-139/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/8/82063/2228024-hero.jpg",
    },
    UPS.WIN: {
        "id": 94,
        "slug": "pc",
        "title": "PC",
        "description": "The PC (Personal Computer) is a highly configurable and upgradable gaming platform that, among home systems, sports the widest variety of control methods, largest library of games, and cutting edge graphics and sound capabilities.",
        "url": "https://www.giantbomb.com/pc/3045-94/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/3661/1650285-ibm_pc_5150.jpg",
    },
    UPS.WINDOWS_MOBILE: {
        "id": 124,
        "slug": "windows-phone",
        "title": "Windows Phone",
        "description": "A now-discontinued smartphone OS made by Microsoft, which had built-in integration with Xbox Live and other services.",
        "url": "https://www.giantbomb.com/windows-phone/3045-124/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3383080-9699565116-windo.jpg",
    },
    UPS.WONDERSWAN: {
        "id": 65,
        "slug": "wonderswan",
        "title": "WonderSwan",
        "description": "The WonderSwan was a Japan-only handheld game system that had a fairly large library of games and many accessories.",
        "url": "https://www.giantbomb.com/wonderswan/3045-65/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954594-wonderswan-black-left.jpg",
    },
    UPS.WONDERSWAN_COLOR: {
        "id": 54,
        "slug": "wonderswan-color",
        "title": "WonderSwan Color",
        "description": "A Handheld gaming device from Bandai. The system was noteworthy for supporting play on the system vertically or horizontally, depending on the particular game.",
        "url": "https://www.giantbomb.com/wonderswan-color/3045-54/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/25/176139-wswpeablu.jpg",
    },
    UPS.X1: {
        "id": 113,
        "slug": "sharp-x1",
        "title": "Sharp X1",
        "description": "The first in Sharp's X line of computers. It was the successor to the Sharp MZ, and was in turn succeeded by the Sharp X68000.",
        "url": "https://www.giantbomb.com/sharp-x1/3045-113/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/5/59247/1129861-sharpx1.jpg",
    },
    UPS.XAVIXPORT: {
        "id": 132,
        "slug": "xavixport",
        "title": "XaviXPORT",
        "description": "The XaviXPORT is a fitness-oriented system that works with cartridges and fitness gear, like specialized golf clubs, boxing clubs, and baseball bats.",
        "url": "https://www.giantbomb.com/xavixport/3045-132/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954582-xavix-xavixport-console-fl.jpg",
    },
    UPS.XBOX: {
        "id": 32,
        "slug": "xbox",
        "title": "Xbox",
        "description": "Microsoft's first home gaming system and one of the first to include an internal hard drive and built in online play capability. It was considered the first console to have fully supported meaningful online play.",
        "url": "https://www.giantbomb.com/xbox/3045-32/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/3699/359843-xbox.jpg",
    },
    UPS.XBOX360: {
        "id": 20,
        "slug": "xbox-360",
        "title": "Xbox 360",
        "description": "The Xbox 360 is the second game console produced by Microsoft Corporation and is the successor to the original Xbox.",
        "url": "https://www.giantbomb.com/xbox-360/3045-20/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3792703-0260626949-05051.jpg",
    },
    UPS.XBOXONE: {
        "id": 145,
        "slug": "xbox-one",
        "title": "Xbox One",
        "description": "The Xbox One is Microsoft's third video game console. It was released on November 22, 2013 in thirteen countries.",
        "url": "https://www.giantbomb.com/xbox-one/3045-145/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/2485895-xboxd_logo_consle_sensr_controller_f_greenbg_rgb_2013_610x610.jpg",
    },
    UPS.ZEEBO: {
        "id": 122,
        "slug": "zeebo",
        "title": "Zeebo",
        "description": "The Zeebo was a wireless network-enabled console primarily designed for emerging markets.",
        "url": "https://www.giantbomb.com/zeebo/3045-122/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/8/86078/1391294-zeebo.jpg",
    },
    UPS.ZODIAC: {
        "id": 64,
        "slug": "zodiac",
        "title": "Zodiac",
        "description": "A Palm based PDA/Portable games console with a touch screen, which for a short time had an active homebrew community. It was released in two different editions with different amounts of onboard memory, the Zodiac 1 (32MB) and the Zodiac 2 (128MB).",
        "url": "https://www.giantbomb.com/zodiac/3045-64/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954587-tapwave-zodiac2-fl.jpg",
    },
    UPS.ZXS: {
        "id": 16,
        "slug": "zx-spectrum",
        "title": "ZX Spectrum",
        "description": "The ZX Spectrum is one of the most popular European computers of all time.  Its software library is enormous and its fame in Europe rivals the Commodore 64 in the US.",
        "url": "https://www.giantbomb.com/zx-spectrum/3045-16/",
        "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/25/176104-zxspectrum48k.jpg",
    },
}

#  UPS.PS6: {
#     "id": 212,
#     "slug": "next-generation-playstation",
#     "title": "Next Generation PlayStation",
#     "description": "The sixth PlayStation console developed by Sony.",
#     "url": "https://www.giantbomb.com/next-generation-playstation/3045-212/",
#     "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3791677-logo.png",
# },
# UPS.XBOX5: {
#     "id": 211,
#     "slug": "next-generation-xbox",
#     "title": "Next Generation Xbox",
#     "description": "The fifth Xbox console was first mentioned by Xbox President, Sarah Bond, in February 2024.",
#     "url": "https://www.giantbomb.com/next-generation-xbox/3045-211/",
#     "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3600344-9619474977-2048p.png",
# },
# UPS.PSN_VITA: {
#     "id": 143,
#     "slug": "playstation-network-vita",
#     "title": "PlayStation Network (Vita)",
#     "description": "The PlayStation Network is Sony's digital storefront for delivering games, add-ons, and other content. This specific platform page focuses on the PlayStation Vita version of said storefront.",
#     "url": "https://www.giantbomb.com/playstation-network-vita/3045-143/",
#     "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/2124933-psnpsv1.png",
# },
# UPS.NINTENDO_3DS_ESHOP: {
#     "id": 138,
#     "slug": "nintendo-3ds-eshop",
#     "title": "Nintendo 3DS eShop",
#     "description": "The products that make up the various segments of Nintendo's 3DS eShop include new releases, updated version of old games, and emulated versions of old games.",
#     "url": "https://www.giantbomb.com/nintendo-3ds-eshop/3045-138/",
#     "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3383078-9903589581-3DS-e.jpg",
# },
# UPS.NINTENDO_DSI_WARE: {
#     "id": 106,
#     "slug": "dsiware",
#     "title": "DSiWare",
#     "description": "DSiWare is Nintendo's name for its downloadable games appearing on the new Nintendo DSi system.",
#     "url": "https://www.giantbomb.com/dsiware/3045-106/",
#     "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/26/847036-dsiware.jpg",
# },
# UPS.PLAYSTATION_NETWORK_PSP: {
#     "id": 116,
#     "slug": "playstation-network-psp",
#     "title": "PlayStation Network (PSP)",
#     "description": "This platform is specifically for PSP releases that are made available as digital downloads via the PlayStation Store. The Store includes PSP games (some exclusive to PSN), PSP Minis, PSone Classics, trailers, movies, TV shows, and digital comics.",
#     "url": "https://www.giantbomb.com/playstation-network-psp/3045-116/",
#     "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/2122556-psnpsp.png",
# },
# UPS.WII_SHOP: {
#     "id": 87,
#     "slug": "wii-shop",
#     "title": "Wii Shop",
#     "description": "The Wii Shop Channel was Nintendo's way of digitally distributing games. It includes WiiWare for newly developed games, as well as the Virtual Console for classic titles from various consoles and arcade systems.",
#     "url": "https://www.giantbomb.com/wii-shop/3045-87/",
#     "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/4647/2954586-1461028228-maxre.jpg",
# },
# UPS.PSN_PS3: {
#     "id": 88,
#     "slug": "playstation-network-ps3",
#     "title": "PlayStation Network (PS3)",
#     "description": "The PlayStation Network is the online service by Sony Computer Entertainment, providing downloads of games, trailers, themes and much more. The service is free, but also offers a paid version for various benefits.",
#     "url": "https://www.giantbomb.com/playstation-network-ps3/3045-88/",
#     "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/2122559-psnps3.png",
# },
# UPS.XBOX_360_GAMES_STORE: {
#     "id": 86,
#     "slug": "xbox-360-games-store",
#     "title": "Xbox 360 Games Store",
#     "description": "Xbox Live Games Store was an online store for the Xbox 360 and Xbox One which allows users to purchase games digitally. The service was shut down on July 29th, 2024.",
#     "url": "https://www.giantbomb.com/xbox-360-games-store/3045-86/",
#     "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/2564457-8881913767-XboxL.png",
# },
# UPS._3DO_M2: {
#     "id": 203,
#     "slug": "m2",
#     "title": "M2",
#     "description": "The M2 was a console developed by The 3DO Company. It was originally intended to be an add-on to the 3DO console, but later transitioned into a full-on successor before Panasonic (Matsushita) canceled the project in 1997. The hardware was later implemented in other appliances.",
#     "url": "https://www.giantbomb.com/m2/3045-203/",
#     "url_logo": "https://www.giantbomb.com/a/uploads/square_small/0/1992/3306128-91e5b27a651edbf791d7830c2eb725d2.jpg",
# },
