from typing import TypedDict

from .base_hander import MetadataHandler


class TGDBHandler(MetadataHandler):
    def __init__(self) -> None:
        self.BASE_URL = "https://api.thegamesdb.net/v1"
        self.platform_endpoint = f"{self.BASE_URL}/Lookup/Platforms"
        self.games_endpoint = f"{self.BASE_URL}/Lookup/ByHash"


class SlugToTGDBId(TypedDict):
    id: int
    name: str


TGDB_PLATFORM_LIST: dict[str, SlugToTGDBId] = {
    "3do": {"id": 25, "name": "3DO"},
    "acorn-archimedes": {"id": 4944, "name": "Acorn Archimedes"},
    "atom": {"id": 5014, "name": "Acorn Atom"},
    "acorn-electron": {"id": 4954, "name": "Acorn Electron"},
    "action-max": {"id": 4976, "name": "Action Max"},
    "amiga": {"id": 4911, "name": "Amiga"},
    "amiga-cd32": {"id": 4947, "name": "Amiga CD32"},
    "acpc": {"id": 4914, "name": "Amstrad CPC"},
    "amstrad-gx4000": {"id": 4999, "name": "Amstrad GX4000"},
    "android": {"id": 4916, "name": "Android"},
    "apf": {"id": 4969, "name": "APF MP-1000"},
    "appleii": {"id": 4942, "name": "Apple II"},
    "apple-pippin": {"id": 5001, "name": "Apple Pippin"},
    "arcade": {"id": 23, "name": "Arcade"},
    "atari2600": {"id": 22, "name": "Atari 2600"},
    "atari5200": {"id": 26, "name": "Atari 5200"},
    "atari7800": {"id": 27, "name": "Atari 7800"},
    "atari800": {"id": 4943, "name": "Atari 800"},
    "jaguar": {"id": 28, "name": "Atari Jaguar"},
    "atari-jaguar-cd": {"id": 29, "name": "Atari Jaguar CD"},
    "lynx": {"id": 4924, "name": "Atari Lynx"},
    "atari-st": {"id": 4937, "name": "Atari ST"},
    "atari-xegs": {"id": 30, "name": "Atari XEGS"},
    "astrocade": {"id": 4968, "name": "Bally Astrocade"},
    "bbcmicro": {"id": 5013, "name": "BBC Micro"},
    "casio-loopy": {"id": 4991, "name": "Casio Loopy"},
    "casio-pv-1000": {"id": 4964, "name": "Casio PV-1000"},
    "telstar-arcade": {"id": 4970, "name": "Coleco Telstar Arcade"},
    "colecovision": {"id": 31, "name": "Colecovision"},
    "c128": {"id": 4946, "name": "Commodore 128"},
    "c16": {"id": 5006, "name": "Commodore 16"},
    "c64": {"id": 40, "name": "Commodore 64"},
    "cpet": {"id": 5008, "name": "Commodore PET"},
    "c-plus-4": {"id": 5007, "name": "Commodore Plus/4"},
    "vic-20": {"id": 4945, "name": "Commodore VIC-20"},
    "didj": {"id": 5012, "name": "Didj"},
    "dragon-32-slash-64": {"id": 4952, "name": "Dragon 32/64"},
    "arcadia-2001": {"id": 4963, "name": "Emerson Arcadia 2001"},
    "adventure-vision": {"id": 4974, "name": "Entex Adventure Vision"},
    "epoch-cassette-vision": {"id": 4965, "name": "Epoch Cassette Vision"},
    "epoch-super-cassette-vision": {"id": 4966, "name": "Epoch Super Cassette Vision"},
    "evercade": {"id": 4985, "name": "Evercade"},
    "fairchild-channel-f": {"id": 4928, "name": "Fairchild Channel F"},
    "fds": {"id": 4936, "name": "Famicom Disk System"},
    "fm-towns": {"id": 4932, "name": "FM Towns Marty"},
    "fm-7": {"id": 4978, "name": "Fujitsu FM-7"},
    "gamate": {"id": 5004, "name": "Gamate"},
    "g-and-w": {"id": 4950, "name": "Game & Watch"},
    "game-wave": {"id": 5002, "name": "Game Wave"},
    "game-dot-com": {"id": 4940, "name": "Game.com"},
    "gizmondo": {"id": 4992, "name": "Gizmondo"},
    "gp32": {"id": 5015, "name": "GP32"},
    "handheld-electronic-lcd": {"id": 4951, "name": "Handheld Electronic Games (LCD)"},
    "hyperscan": {"id": 4987, "name": "HyperScan"},
    "intellivision": {"id": 32, "name": "Intellivision"},
    "vc-4000": {"id": 4994, "name": "Interton VC 4000"},
    "ios": {"id": 4915, "name": "iOS"},
    "j2me": {"id": 5018, "name": "J2ME"},
    "jupiter-ace": {"id": 5019, "name": "Jupiter Ace"},
    "mac": {"id": 37, "name": "Mac OS"},
    "odyssey--1": {"id": 4961, "name": "Magnavox Odyssey 1"},
    "odyssey-2-slash-videopac-g7000": {"id": 4927, "name": "Magnavox Odyssey 2"},
    "aquarius": {"id": 4989, "name": "Mattel Aquarius"},
    "mega-duck-slash-cougar-boy": {"id": 4948, "name": "Mega Duck"},
    "xbox": {"id": 14, "name": "Microsoft Xbox"},
    "xbox360": {"id": 15, "name": "Microsoft Xbox 360"},
    "xboxone": {"id": 4920, "name": "Microsoft Xbox One"},
    "series-x-s": {"id": 4981, "name": "Microsoft Xbox Series X/S"},
    "microvision": {"id": 4972, "name": "Milton Bradley Microvision"},
    "msx": {"id": 4929, "name": "MSX"},
    "ngage": {"id": 4938, "name": "N-Gage"},
    "neogeoaes": {"id": 24, "name": "Neo Geo AES"},
    "neogeomvs": {"id": 24, "name": "Neo Geo MVS"},
    "neo-geo-cd": {"id": 4956, "name": "Neo Geo CD"},
    "neo-geo-pocket": {"id": 4922, "name": "Neo Geo Pocket"},
    "neo-geo-pocket-color": {"id": 4923, "name": "Neo Geo Pocket Color"},
    "3ds": {"id": 4912, "name": "Nintendo 3DS"},
    "n64": {"id": 3, "name": "Nintendo 64"},
    "nds": {"id": 8, "name": "Nintendo DS"},
    "nes": {"id": 7, "name": "Nintendo Entertainment System (NES)"},
    "gb": {"id": 4, "name": "Nintendo Game Boy"},
    "gba": {"id": 5, "name": "Nintendo Game Boy Advance"},
    "gbc": {"id": 41, "name": "Nintendo Game Boy Color"},
    "ngc": {"id": 2, "name": "Nintendo GameCube"},
    "pokemon-mini": {"id": 4957, "name": "Nintendo Pokémon Mini"},
    "switch": {"id": 4971, "name": "Nintendo Switch"},
    "switch2": {"id": 5021, "name": "Nintendo Switch 2"},
    "virtualboy": {"id": 4918, "name": "Nintendo Virtual Boy"},
    "wii": {"id": 9, "name": "Nintendo Wii"},
    "wiiu": {"id": 38, "name": "Nintendo Wii U"},
    "nuon": {"id": 4935, "name": "Nuon"},
    "oculus-quest": {"id": 4990, "name": "Oculus Quest"},
    "oric": {"id": 4986, "name": "Oric 1"},
    "ouya": {"id": 4921, "name": "Ouya"},
    "palmtex": {"id": 5003, "name": "Palmtex Super Micro"},
    "win": {"id": 1, "name": "PC"},
    "pc-8800-series": {"id": 4933, "name": "PC-88"},
    "pc-9800-series": {"id": 4934, "name": "PC-98"},
    "pc-fx": {"id": 4930, "name": "PC-FX"},
    "philips-cd-i": {"id": 4917, "name": "Philips CD-i"},
    "tele-spiel": {"id": 4993, "name": "Philips Tele-Spiel ES-2201"},
    "laseractive": {"id": 4975, "name": "Pioneer LaserActive"},
    "playdate": {"id": 5016, "name": "Playdate"},
    "playdia": {"id": 5000, "name": "Playdia"},
    "r-zone": {"id": 4983, "name": "R-Zone"},
    "rca-studio-ii": {"id": 4967, "name": "RCA Studio II"},
    "sam-coupe": {"id": 4979, "name": "SAM Coupé"},
    "sega32": {"id": 33, "name": "Sega 32X"},
    "segacd": {"id": 21, "name": "Sega CD"},
    "dc": {"id": 16, "name": "Sega Dreamcast"},
    "gamegear": {"id": 20, "name": "Sega Game Gear"},
    "genesis-slash-megadrive": {"id": 18, "name": "Sega Genesis"},
    "sms": {"id": 35, "name": "Sega Master System"},
    "sega-pico": {"id": 4958, "name": "Sega Pico"},
    "saturn": {"id": 17, "name": "Sega Saturn"},
    "sg-1000": {"id": 4949, "name": "SEGA SG-1000"},
    "x1": {"id": 4977, "name": "Sharp X1"},
    "sharp-x68000": {"id": 4931, "name": "Sharp X68000"},
    "black-point": {"id": 4996, "name": "SHG Black Point"},
    "sinclair-ql": {"id": 5020, "name": "Sinclair QL"},
    "zxs": {"id": 4913, "name": "Sinclair ZX Spectrum"},
    "zx80": {"id": 5009, "name": "Sinclair ZX80"},
    "zx81": {"id": 5010, "name": "Sinclair ZX81"},
    "ps": {"id": 10, "name": "Sony Playstation"},
    "ps2": {"id": 11, "name": "Sony Playstation 2"},
    "ps3": {"id": 12, "name": "Sony Playstation 3"},
    "ps4--1": {"id": 4919, "name": "Sony Playstation 4"},
    "ps5": {"id": 4980, "name": "Sony Playstation 5"},
    "psp": {"id": 13, "name": "Sony Playstation Portable"},
    "psvita": {"id": 39, "name": "Sony Playstation Vita"},
    "stadia": {"id": 5011, "name": "Stadia"},
    "snes": {"id": 6, "name": "Super Nintendo (SNES)"},
    "tandy-vis": {"id": 4982, "name": "Tandy Visual Interactive System"},
    "zod": {"id": 5017, "name": "Tapwave Zodiac"},
    "ti-994a": {"id": 4953, "name": "Texas Instruments TI-99/4A"},
    "tomy-tutor": {"id": 4960, "name": "Tomy Tutor"},
    "trs-80": {"id": 4941, "name": "TRS-80 Color Computer"},
    "turbografx16--1": {"id": 34, "name": "TurboGrafx 16"},
    "turbografx-cd": {"id": 4955, "name": "TurboGrafx CD"},
    "vsmile": {"id": 4988, "name": "V.Smile"},
    "vectrex": {"id": 4939, "name": "Vectrex"},
    "creativision": {"id": 5005, "name": "VTech CreatiVision"},
    "socrates": {"id": 4998, "name": "VTech Socrates"},
    "supervision": {"id": 4959, "name": "Watara Supervision"},
    "wonderswan": {"id": 4925, "name": "WonderSwan"},
    "wonderswan-color": {"id": 4926, "name": "WonderSwan Color"},
    "xavixport": {"id": 4984, "name": "Xavix Port"},
}
