apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "romm.fullname" . }}-config
  labels:
    {{- include "romm.labels" . | nindent 4 }}
data:
  config.yml: |-
  {{- .Values.romm.settings | toYaml | nindent 4 }}