{{- if .Values.romm.config.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "romm-secret"
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "auth-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $authSecret to existing secret data or generate a random one when not exists
  {{- $authSecret := (get $secretData "auth-secret") | default (randAlphaNum 32) }}
  auth-secret: {{ $authSecret | quote }}
{{- end }}