{{- range .Values.romm.mediaVolumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "romm.fullname" $ }}-mediavol-{{ .name }}
  labels:
    {{- include "romm.labels" $ | nindent 4 }}
    {{- with $.Values.global.commonLabels }}{{ toYaml . | nindent 4 }}{{ end }}
spec:
  storageClassName: ""
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" $ | nindent 6 }}
      romm-volume: {{ .name }}
  accessModes: {{ toYaml .volumeSpec.accessModes | nindent 4 }}
  resources:
    requests: {{ toYaml .volumeSpec.capacity | nindent 6 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "romm.fullname" $ }}-mediavol-{{ .name }}
  labels:
    {{- include "romm.labels" $ | nindent 4 }}
    {{- with $.Values.global.commonLabels }}{{ toYaml . | nindent 4 }}{{ end }}
    romm-volume: {{ .name }}
spec: {{ toYaml .volumeSpec | nindent 2 }}
{{- end }}
