"""Rebuild the materialized virtual_collections table.

`virtual_collections` is a whole-library aggregation (every rom's facets grouped
with a ``> 2`` membership threshold), so it can only be rebuilt in full, not
maintained per rom. It is rebuilt here, driven by a debounced background job
that is kicked off whenever the library changes (issue #3768). Bursts of rom
edits collapse into a single scheduled run.
"""

from datetime import timedelta
from itertools import chain

from rq.job import Job

from config import TASK_TIMEOUT
from handler.database import db_collection_handler
from handler.redis_handler import get_job_func_name, low_prio_queue
from logger.logger import log
from tasks.tasks import Task, TaskType, tasks_scheduler
from utils.context import initialize_context

# Collapse a burst of rom changes into one rebuild: the first change schedules a
# run this far in the future, and subsequent changes find it already pending.
REBUILD_DEBOUNCE_SECONDS = 30
_REBUILD_FUNC_NAME = "run_virtual_collections_rebuild"


def run_virtual_collections_rebuild() -> None:
    """Rebuild the whole materialized virtual_collections table."""
    log.info("Rebuilding virtual collections...")
    db_collection_handler.rebuild_virtual_collections()
    log.info("Virtual collections rebuild complete")


def _rebuild_pending() -> bool:
    """True if a rebuild is already scheduled or waiting in the queue.

    A pending job runs later and reads the current DB state, so it already
    covers any change made before it fires; only a started job doesn't.
    """
    for job in chain(tasks_scheduler.get_jobs(), low_prio_queue.get_jobs()):
        if (
            isinstance(job, Job)
            and get_job_func_name(job) == _REBUILD_FUNC_NAME
            and not job.is_started
        ):
            return True
    return False


def enqueue_virtual_collections_rebuild() -> None:
    """Schedule a debounced rebuild, unless one is already pending."""
    try:
        if _rebuild_pending():
            return
        tasks_scheduler.enqueue_in(
            timedelta(seconds=REBUILD_DEBOUNCE_SECONDS),
            run_virtual_collections_rebuild,
            job_timeout=TASK_TIMEOUT,
        )
    except Exception as e:  # never let cache maintenance break a write
        log.warning(f"Could not enqueue virtual collections rebuild: {e}")


class RebuildVirtualCollectionsTask(Task):
    def __init__(self) -> None:
        super().__init__(
            title="Rebuild virtual collections",
            description=(
                "Recompute the autogenerated virtual collections (by genre, "
                "franchise, company, game mode and IGDB collection) from the "
                "current library."
            ),
            task_type=TaskType.CLEANUP,
            enabled=True,
            manual_run=True,
            cron_string=None,
        )

    @initialize_context()
    async def run(self) -> None:
        log.info(f"Starting {self.title} task...")
        run_virtual_collections_rebuild()


rebuild_virtual_collections_task = RebuildVirtualCollectionsTask()
