export const EMULATOR_CORE_MAP: Record<string, string> = {
  arcade: "mame2003_plus",
  mame: "mame2003_plus",
  nes: "nes",
  famicom: "nes",
  snes: "snes",
  supernintendo: "snes",
  superfamicom: "snes",
  n64: "n64",
  gb: "gb",
  gbc: "gbc",
  gba: "gba",
  genesis: "segaMD",
  megadrive: "segaMD",
  master_system: "sms",
  mastersystem: "sms",
  sms: "sms",
  gg: "gg",
  gamegear: "gg",
  saturn: "sat",
  psx: "psx",
  ps1: "psx",
  playstation: "psx",
  ps2: "ps2",
  ps3: "ps3",
  psp: "psp",
  atari2600: "a26",
  atari7800: "a78",
  lynx: "lynx",
  atarilynx: "lynx",
  vb: "vb",
  virtualboy: "vb",
  wonderswan: "ws",
  wonderswancolor: "wsc",
  ngp: "ngp",
  neogeopocket: "ngp",
  ngpc: "ngpc",
  neogeopocketcolor: "ngpc",
  pce: "pce",
  pcengine: "pce",
  tg16: "pce",
  sgx: "sgx",
  pcfx: "pcfx",
  msx: "msx",
  msx2: "msx2",
  gamecube: "gc",
  gc: "gc",
};

export function getCoreForPlatform(platformSlug: string): string | null {
  return EMULATOR_CORE_MAP[platformSlug.toLowerCase()] || null;
}
