export interface SupportedPlatformDef {
  label: string;
  slugs: string[];
  assetSlug?: string; // slug used to pick an image (if different)
  image?: string; // explicit image path
  background?: string; // gradient/background css
  accent?: string; // accent color
  shortName?: string; // fallback short label for cards
}
export const SUPPORTED_PLATFORMS: SupportedPlatformDef[] = [
  {
    label: "3DO",
    slugs: ["3do", "panasonic3do"],
    shortName: "3DO",
    image: "/systems/3do.webp",
    background: "linear-gradient(135deg,#4e4376,#2b5876)",
    accent: "#6f63b4",
  },
  {
    label: "Amiga",
    slugs: ["amiga"],
    shortName: "Amiga",
    image: "/systems/amiga.webp",
    background: "linear-gradient(135deg,#0093e9,#80d0c7)",
    accent: "#33b1ff",
  },
  {
    label: "Arcade / MAME",
    slugs: ["arcade", "mame"],
    shortName: "Arcade",
    image: "/systems/arcade.webp",
    background: "linear-gradient(135deg,#d73266,#8b1538)",
    accent: "#d73266",
  },
  {
    label: "Atari 2600",
    slugs: ["atari2600"],
    shortName: "2600",
    image: "/systems/atari2600.webp",
    background: "linear-gradient(135deg,#c04848,#480048)",
    accent: "#ff6a6a",
  },
  {
    label: "Atari 5200",
    slugs: ["atari5200"],
    shortName: "5200",
    image: "/systems/atari5200.webp",
    background: "linear-gradient(135deg,#3a6073,#16222a)",
    accent: "#4fa3c7",
  },
  {
    label: "Atari 7800",
    slugs: ["atari7800"],
    shortName: "7800",
    image: "/systems/atari7800.webp",
    background: "linear-gradient(135deg,#870000,#190a05)",
    accent: "#ff3030",
  },
  {
    label: "Atari Jaguar",
    slugs: ["jaguar", "atarijaguar"],
    shortName: "Jaguar",
    image: "/systems/jaguar.webp",
    background: "linear-gradient(135deg,#000000,#434343)",
    accent: "#ff0015",
  },
  {
    label: "Atari Lynx",
    slugs: ["lynx", "atarilynx"],
    shortName: "Lynx",
    image: "/systems/lynx.webp",
    background: "linear-gradient(135deg,#485563,#29323c)",
    accent: "#ffa733",
  },
  {
    label: "Commodore 64",
    slugs: ["c64", "commodore64"],
    shortName: "C64",
    image: "/systems/c64.webp",
    background: "linear-gradient(135deg,#614385,#516395)",
    accent: "#8b7ad6",
  },
  {
    label: "ColecoVision",
    slugs: ["colecovision"],
    shortName: "Coleco",
    image: "/systems/coleco.webp",
    background: "linear-gradient(135deg,#134e5e,#71b280)",
    accent: "#34c686",
  },
  {
    label: "DOOM",
    slugs: ["doom"],
    shortName: "DOOM",
    image: "/systems/doom.webp",
    background: "linear-gradient(135deg,#636363,#0f0f0f)",
    accent: "#ff9800",
  },
  {
    label: "Neo Geo Pocket",
    slugs: ["ngp", "neogeopocket"],
    shortName: "NGP",
    image: "/systems/ngp.webp",
    background: "linear-gradient(135deg,#1e3c72,#2a5298)",
    accent: "#2e6dff",
  },
  {
    label: "Neo Geo Pocket Color",
    slugs: ["ngpc", "neogeopocketcolor"],
    shortName: "NGPC",
    image: "/systems/ngpc.webp",
    background: "linear-gradient(135deg,#42275a,#734b6d)",
    accent: "#b667d0",
  },
  {
    label: "MS-DOS",
    slugs: ["dos", "msdos"],
    shortName: "DOS",
    image: "/systems/dos.webp",
    background: "linear-gradient(135deg,#203a43,#2c5364)",
    accent: "#3fa7d6",
  },
  {
    label: "Nintendo 64",
    slugs: ["n64"],
    shortName: "N64",
    image: "/systems/n64.webp",
    background: "linear-gradient(135deg,#ffd700,#ff8c00)",
    accent: "#ffd700",
  },
  {
    label: "Nintendo Entertainment System (NES)",
    slugs: ["nes", "famicom"],
    shortName: "NES",
    image: "/systems/nes.webp",
    background: "linear-gradient(135deg,#cc2936,#8b1538)",
    accent: "#cc2936",
  },
  {
    label: "Nintendo Family Computer (Famicom)",
    slugs: ["famicom"],
    shortName: "Famicom",
    image: "/systems/nes.webp",
    background: "linear-gradient(135deg,#cc2936,#8b1538)",
    accent: "#cc2936",
  },
  {
    label: "Nintendo DS",
    slugs: ["nds", "ds"],
    shortName: "NDS",
    image: "/systems/nds.webp",
    background: "linear-gradient(135deg,#56ccf2,#2f80ed)",
    accent: "#2f80ed",
  },
  {
    label: "Game Boy",
    slugs: ["gb"],
    shortName: "GB",
    image: "/systems/gbc.webp",
    background: "linear-gradient(135deg,#8fbc8f,#556b2f)",
    accent: "#8fbc8f",
  },
  {
    label: "Game Boy Color",
    slugs: ["gbc"],
    shortName: "GBC",
    image: "/systems/gbc.webp",
    background: "linear-gradient(135deg,#20b2aa,#008b8b)",
    accent: "#20b2aa",
  },
  {
    label: "Game Boy Advance",
    slugs: ["gba"],
    shortName: "GBA",
    image: "/systems/gba.webp",
    background: "linear-gradient(135deg,#9370db,#4b0082)",
    accent: "#9370db",
  },
  {
    label: "PC-FX",
    slugs: ["pcfx", "pc-fx"],
    shortName: "PC-FX",
    image: "/systems/pcfx.webp",
    background: "linear-gradient(135deg,#41295a,#2f0743)",
    accent: "#b44cff",
  },
  {
    label: "PlayStation (PS)",
    slugs: ["psx", "ps1", "playstation"],
    shortName: "PS1",
    image: "/systems/psx.webp",
    background: "linear-gradient(135deg,#4169e1,#191970)",
    accent: "#4169e1",
  },
  {
    label: "Sega 32X",
    slugs: ["32x", "sega32x"],
    shortName: "32X",
    image: "/systems/32x.webp",
    background: "linear-gradient(135deg,#f7971e,#ffd200)",
    accent: "#ffbf00",
  },
  {
    label: "Sega CD",
    slugs: ["segacd", "megacd"],
    shortName: "Sega CD",
    image: "/systems/segacd.webp",
    background: "linear-gradient(135deg,#2980b9,#2c3e50)",
    accent: "#4fa3ff",
  },
  {
    label: "Sega Game Gear",
    slugs: ["gamegear", "gg"],
    shortName: "GG",
    image: "/systems/gamegear.webp",
    background: "linear-gradient(135deg,#141e30,#243b55)",
    accent: "#4f7fbf",
  },
  {
    label: "Sega Master System",
    slugs: ["mastersystem", "sms"],
    shortName: "SMS",
    image: "/systems/sms.webp",
    background: "linear-gradient(135deg,#ff6347,#dc143c)",
    accent: "#ff6347",
  },
  {
    label: "Sega Genesis / Megadrive",
    slugs: ["genesis", "megadrive"],
    shortName: "Genesis",
    image: "/systems/genesis.webp",
    background: "linear-gradient(135deg,#1e90ff,#0f4c75)",
    accent: "#1e90ff",
  },
  {
    label: "Sega Saturn",
    slugs: ["saturn"],
    shortName: "Saturn",
    image: "/systems/saturn.webp",
    background: "linear-gradient(135deg,#141e30,#243b55)",
    accent: "#4f7fbf",
  },
  {
    label: "Super Nintendo Entertainment System (SNES)",
    slugs: ["snes", "supernintendo", "superfamicom"],
    shortName: "SNES",
    image: "/systems/snes.webp",
    background: "linear-gradient(135deg,#e22828,#f81414)",
    accent: "#e22828",
  },
  {
    label: "Super Famicom",
    slugs: ["superfamicom"],
    shortName: "SFC",
    image: "/systems/snes.webp",
    background: "linear-gradient(135deg,#e22828,#f81414)",
    accent: "#e22828",
  },
  {
    label: "TurboGrafx-16 / PC Engine",
    slugs: ["tg16", "pcengine", "pce"],
    shortName: "TG-16",
    image: "/systems/pcengine.webp",
    background: "linear-gradient(135deg,#ff9966,#ff5e62)",
    accent: "#ff7b54",
  },
  {
    label: "Virtual Boy",
    slugs: ["virtualboy"],
    shortName: "VBoy",
    image: "/systems/virtualboy.webp",
    background: "linear-gradient(135deg,#8e0e00,#1f1c18)",
    accent: "#ff2a2a",
  },
  {
    label: "WonderSwan",
    slugs: ["wonderswan"],
    shortName: "WS",
    image: "/systems/wonderswan.webp",
    background: "linear-gradient(135deg,#457fca,#5691c8)",
    accent: "#4f8edb",
  },
  {
    label: "WonderSwan Color",
    slugs: ["wonderswancolor"],
    shortName: "WSC",
    image: "/systems/wonderswancolor.webp",
    background: "linear-gradient(135deg,#396afc,#2948ff)",
    accent: "#456dff",
  },
];
export const SUPPORTED_WEB_PLATFORM_SET = new Set<string>(
  SUPPORTED_PLATFORMS.flatMap((p) => p.slugs)
);

// Map any individual slug/alias to its full theme definition for quick lookup.
export const PLATFORM_THEME_BY_SLUG: Record<string, SupportedPlatformDef> =
  (() => {
    const map: Record<string, SupportedPlatformDef> = {};
    for (const def of SUPPORTED_PLATFORMS) {
      for (const s of def.slugs) map[s] = def;
    }
    return map;
  })();
