name: Build Docker Image on Test Tag

on:
  push:
    tags:
      - "test-*"

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.3.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: |
            name=ghcr.io/${{ github.repository }}/romm-test
          tags: |
            type=match,pattern=test-*,group=0

      - name: Build full image
        uses: docker/build-push-action@v6.18.0
        with:
          file: docker/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: full-image
