name: Run Trunk Check

on:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  trunk_check:
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.0
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1.2.4
